### ISSUE TITLE
Documentation broken?

### ISSUE THREAD

**Issue by trayres** [graphics32/graphics32#10]
http://graphics32.org/documentation/Docs/_Body.htm

It looks like the web links for the documentation don't work.

**Comment by micha137** [comment]
I offer to host the docs and keep them up to date.

Btw, any graphics32.org URL seems to redirect to GitHub.

**Comment by CWBudde** [comment]
I think it would be better to stick with GitHub for the documentation. We could use the https://pages.github.com/ to host the content directly from the sources. An additional repository and some configuration should be satisfying in this regards.

**Comment by CWBudde** [comment]
Eventually we could even use the 'Wiki' featurs as wikis are just git repositories itself. This however would mean that we should need another processor to bring the content we already have into the right format...

**Comment by micha137** [comment]
I don't want to change the whole system, which takes more effort.  I like the documentation the way it is, because it can also be used offline, very fast.  I don't see an advantage of easier editing through a wiki over pull requests to the existing doc sources.

**Comment by CWBudde** [comment]
I agree here. So the easiest would be to just upload the existing documentation to a new git sub repository and link the content with github pages.

**Comment by CWBudde** [comment]
The documentation can now be found here: https://graphics32.github.io/Docs/
However, it still needs to get referenced properly

**Comment by trayres** [comment]
That link works a charm, thanks!

**Comment by micha137** [comment]
>  it still needs to get referenced properly

@CWBudde: Do you mean someone has to update the link from graphics32.org?  Who has the access? Do you know anything about the forwarding to github?

**Comment by CWBudde** [comment]
I've already contacted Andre who owns the current server. IIRC, he took down the documentation because of some security issues and AFAIR he expressed the wish to move everything over to GitHub.

In my email I asked him if he is aware of a solution to move the existing stuff (website, wiki) to GitHub. The original site was based on "Wiki Wiki Web" as far as I know, which needs some conversion over to Wikia, which is in use by GitHub. Or we could copy the HTML output over to static HTML files.

Regarding a forward from Graphics32.org: This should be possible directly from GitHub as well, but in the end it's Andre's decision, who still owns the domain.

**Comment by micha137** [comment]
I believe, graphics32.org was running on PMWiki, but that doesn't matter.  Let's see what he replies.  The complete forward from graphics32.org is already active, that is what I wondered about.

**Comment by micha137** [comment]
I added the link above to README.md, so it is discoverable now. Closing this ticket.
