### ISSUE TITLE
EndPath() always closes path

### ISSUE THREAD

**Issue by ThomasNeumann** [graphics32/graphics32#104]
With the most current version EndPath() will close path always when you use MoveTo/LineTo to construct the path.

**Comment by ThomasNeumann** [comment]
`implementation
uses GR32_PATHS, GR32_BRUSHES;

{$R *.dfm}

procedure TForm1.pbTestPaintBuffer(Sender: TObject);
var can32: TCanvas32;
begin
  with pbTest.buffer do begin
    Clear(Color32(self.color));
    can32:= TCanvas32.Create(pbTest.Buffer);
    can32.Brushes.Add(TStrokeBrush);
    (can32.Brushes[0] as TStrokeBrush).StrokeWidth:= 4;
    (can32.Brushes[0] as TStrokeBrush).FillColor:= clYellow32;
    can32.MoveTo(10,10);
    can32.LineTo(200, 200);
    can32.LineTo(33, 180);
    can32.EndPath(False);
    can32.Free;
  end;
end;

end.
` 
This code draws a single line with the  TCanvas32-redesign but with the current version it will close the path

**Comment by lamdalili** [comment]
This probleme is in BuildPolyPolyLine  in relation with #84

**Comment by andersmelander** [comment]
@lamdalili No `BuildPolyPolyLine` has nothing to do with it. I don't know why you would suggest that.

@ThomasNeumann Are you saying that there's no problem when using the **TCanvas32-redesign** branch?
That would surprise me as that branch also draws all paths as polygons.
Apperently this is _as designed_ but in my opinion it should be changed so closed paths are drawn as polygons and open paths are drawn as polylines. Othwerwise there's AFAIK currently no other way to draw a polyline with `TCanvas32` than to use a brush with transparent fill color.

Under any circumstances you should use the **TCanvas32-redesign** branch (merge it into your local master) as bugs in the current version of `TCanvas32` are unlikely to be fixed as it will be replaced by the new version after v2.0 has been released (if that ever happens).

**Comment by ThomasNeumann** [comment]
Hi

Using the TCanvas32-redesign branch it works fine.
I'm confused about the different versions. Using the current Master branch works fine with my code modified to fit the TCanvas32 redesign ( removed all .path entries and BeginPath). So I assumed that the modifications had been merged into the Master branch. ( As you might guess I'm not so common with github :-(

**Comment by lamdalili** [comment]
> No BuildPolyPolyLine has nothing to do with it. I don't know why you would suggest that.
BuildPolyPolyLine  is internally called in TStrokeBrush.PolyPolygonFS and always give closed paths so I replaced the code its by that in #84 which answars on the initial question EndPath() always closes path

with new code 
![closed](https://user-images.githubusercontent.com/40634105/63641332-b5e6ff00-c6ac-11e9-8a58-10142654e509.png)

**Comment by ThomasNeumann** [comment]
Hi,
Just did a test with the master branch, which I loaded down in December 2021. The issue is still there.

**Comment by andersmelander** [comment]
Yes, that's why the issue is still open :-/
I'm afraid that you still have to merge the TCanvas32-redesign branch into mater yourself in order to avoid the problem. Nothing has changed in that regard.

I'm considering what to do about getting the "next version" released. There are currently nobody leading the project so it appears to be pretty much up to me what happens now.
My hope is that I can get the documentation migrated to a wiki somewhere (the github wiki isn't very good) and then just call the current master revision "version 2.0.0". This will be the last version to support old versions of Delphi and any further work to support these old versions of Delphi must happen in a branch. It might also be the last version to actually have a version number.
I will then immediately start merging the stuff that's pending (for example the TCanvas32-redesign branch) into the master branch.

**Comment by ThomasNeumann** [comment]
Thanks.
