### ISSUE TITLE
TCustomBitmap32.LoadFromStream() Error for non-bitmap streams [SOLVED]

### ISSUE THREAD

**Issue by iankrigsman** [graphics32/graphics32#109]
The fallback logic in **TCustomBitmap32.LoadFromStream** expects the stream to be a bitmap...

**Unit: GR32.pas - around line 5226+**
```
procedure TCustomBitmap32.LoadFromStream(Stream: TStream);
<snip>
    B := TBitmap.Create;
    try
      B.LoadFromStream(Stream);
      Assign(B);
    finally
      B.Free;
    end;
```
This raises a format error if, say, the stream was in JPEG format.

By contrast, the fallback logic in **TCustomBitmap32.LoadFromFile** is correct in that it uses a TPicture that can handle various formats.

**Unit: GR32.pas - around line 5308+**
```
procedure TCustomBitmap32.LoadFromFile(const FileName: string);
<snip>
  P := TPicture.Create;
  try
    P.LoadFromFile(FileName);
    Assign(P);
  finally
    P.Free;
  end;
```

Example:
This works:
```
  aBitmap32.LoadFromFile('myImage.jpg');
```

This fails:
```
  aStream := TFileStream.Create('myImage.jpg');
  aBitmap32.LoadFromStream(aStream);
```
FIX: Changing the TBitmap reference to a TPicture (first snippet above) worked for me.

```
procedure TCustomBitmap32.LoadFromStream(Stream: TStream);
var
<snip>
  P: TPicture;
<snip>
    P := TPicture.Create;
    try
      P.LoadFromStream(Stream);
      Assign(P);
    finally
      P.Free;
    end;
```

**Comment by andersmelander** [comment]
`TCustomBitmap32.LoadFromStream` is not the correct place for this functionality. 

`TGraphic.LoadFromStream` is a low level function that should only provide persistence support for the native format of the concrete `TGraphic` class. I.e. `TJPEGImage.LoadFromStream` should only support JPEG, `TBitmap.LoadFromStream` should only support BMP and DIB, etc.
The native format of `TBitmap32` is BMP and as such it should only persist directly to and from this format.

I don't know when file format detection was added to `TPicture`, but it's a fairly recent feature and the fallback in `TCustomBitmap32.LoadFromFile` is a historical leftover from before this.

The current correct way to do fallback is to use the CanLoadFromStream-mechanism and instead of adding fallback to `TCustomBitmap32.LoadFromStream` we should implement `TCustomBitmap32.CanLoadFromStream`. I will create a new issue for this.

Under any circumstances this feature isn't supported by Delphi 7, so it will have to go into a post-2.0 branch.

**Comment by andersmelander** [comment]
I don't know what I was think of when I wrote the above because it's complete nonsense. `TCustomBitmap32` does not descend from `TGraphic` so `TGraphic.CanLoadFromStream` is irrelevant.
