### ISSUE TITLE
Error in handling exceptions in TGaugeBar  

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#112]
When an exception is raised in OnChange evenement the control doesn't detect the correct mouse state. 
```
procedure TForm4.GaugeBar1Change(Sender: TObject);
begin
  if GaugeBar1.Position =50 then
    raise Exception.Create('error');
end;
```
GaugeBar1 will cause exception at position 50  and after that once you close the dialog and when moving cursor over control and "without pressing mouse button" you can see it will change automaticly  its position.

to solve this probleme it is  important to test mouse button by adding this code in the beging of TCustomGaugeBar.MouseMove :
```
  if not (ssLeft in Shift) then
     Exit;
```

**Comment by andersmelander** [comment]
`TRangeBar` and `TGaugeBar` are pretty obsolete and not that robustly implemented and I would not recommend their use.
I suspect they were originally a pet project of one of the main contributors since they don't do anything you couldn't do with a standard windows scrollbar. I would prefer they be removed from Graphics32 ASAP.

Anyway, the correct solution here is to make sure that state is restored if an exception occurs in the `OnChange` event handler. This mean wrapping all code that modifies Position, directly or indirectly, in try...finally to ensure that state is restored.

For example before:

    FGenChange := True;
    Position := FPosBeforeDrag + Delta;
    FGenChange := False;

after:

    FGenChange := True;
    try
      Position := FPosBeforeDrag + Delta;
    finally
      FGenChange := False;
    end;
