### ISSUE TITLE
TBitmap32.SaveToStream flips the saved bitmap vertically

### ISSUE THREAD

**Issue by raelb** [graphics32/graphics32#135]
Hello,
I have attached a sample project illustrating the problem.
I start with a TBitmap, assign it to a TBitmap32 for some processing, then save the TBitmap32 to stream and load it back into a TBitmap.

If I do the below operation (marked "reload the bitmap"), it will flip the bitmap:

    Bmp32.SaveToStream(MemStream);
    Bmp := TBitmap.Create;
    try
      MemStream.Position := 0;
      Bmp.LoadFromStream(MemStream);

      // reload the bitmap -> flips the image...
      MemStream.Clear;
      Bmp.SaveToStream(MemStream);
      MemStream.Position := 0;
      Bmp.LoadFromStream(MemStream);

Is this a bug? It seems wrong, or am I using TBitmap32 incorrectly?

(If you comment out this code, you can see the same effect in the main application when you click on the button "Reload")

Thanks

[Image Flip Test.zip](https://github.com/graphics32/graphics32/files/5090310/Image.Flip.Test.zip)

**Comment by andersmelander** [comment]
The code that exhibits the problem appears to be this:
```
MemStream := TMemoryStream.Create;
try
  Image1.Picture.Bitmap.SaveToStream(MemStream);
  MemStream.Position := 0;
  Image1.Picture.Bitmap.LoadFromStream(MemStream);
finally
  MemStream.Free;
end;
```

Since this code doesn't involve Graphics32 at all I'm inclined to conclude that the problem lies with TBitmap. I'll investigate a bit more.

**Comment by andersmelander** [comment]
The problem is in `TBitmap32.SaveToStream`.
`SaveToStream` has a `SaveTopDown` parameter that specifies if the bitmap should be saved [top-down or bottom-up](https://docs.microsoft.com/en-us/windows/win32/directshow/top-down-vs--bottom-up-dibs). Both formats are valid per the BMP specification. Top-down bitmaps are flagged by specifying a **negative** value in the **biHeight** field of the [`BITMAPINFOHEADER` structure](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapinfoheader) of the bitmap file.

Unfortunately the implementation of `TBitmap32.SaveToStream` reverses the meaning meaning of the `biHeight` field so it will always flip the bitmap vertically regardless of the `SaveTopDown` parameter.

This code was written in 2010 so It's amazing that no one has reported the problem until now.

**Comment by raelb** [comment]
> This code was written in 2010 so It's amazing that no one has reported the problem until now.

It is surprising. Thanks for the fix.
