### ISSUE TITLE
Linear color gradients broken

### ISSUE THREAD

**Issue by CWBudde** [graphics32/graphics32#163]
The pure pascal implementation of the linear color gradients seems to be broken
![PurePascalGradients](https://user-images.githubusercontent.com/4097562/123825107-e928f380-d8fe-11eb-9d75-8560d8eaa81f.png)

Steps to reproduce:

1. Open Example GradFills
2. Add line `{$DEFINE PUREPASCAL}` at the very end of the GR32.inc
3. Compile and find an image like the one above

**Comment by CWBudde** [comment]
The error seems to result from the GR32_Blend unit. In particular a _Pas implementation seems faulty

**Comment by andersmelander** [comment]
Unless you're fixing this yourself, please supply both **Actual** and **Expected** output so it's clear what the problem is. I assume the image you've already supplied is the **Actual**.

**Comment by CWBudde** [comment]
I was writing it down rather for myself. I'm not sure whether I can fix this right now as I would prefer to focus on the Lazarus issues. But this one was not only limited to Lazarus, but to purepascal in general.

I've looked a bit deeper. It seems as if "BlendMemEx_Pas" is the faulty procedure

**Comment by CWBudde** [comment]
It's even not only the BlendMemEx_Pas, but also the BlendMemEx_Asm, that doesn't work as intended. Using the ASM version, the output will be as follows:
![AsmGradients](https://user-images.githubusercontent.com/4097562/123827304-cc8dbb00-d900-11eb-9bf3-6bb6a77944a7.png)

**Comment by CWBudde** [comment]
It seems it comes down to issue #53, but as said, I don't have much time to solve this now. Eventually I should really have a closer look as soon as possible...

**Comment by andersmelander** [comment]
Ah, yes. I had completely forgotten about that old issue (#53). Now that I've read through it again I can see that there are some things that we ought to revisit. The A*B/256 approximation for example can be made precise without any loss of speed.

**Comment by CWBudde** [comment]
I've just added a few hint comment for the SSE2 implementation. Nowadays, only the SSE2 version is used, especially with x64 CPUs where this is guaranteed to be supported. This said, it should be the default to have this. I wouldn't ever had noticed this, if for Lazarus large portions of the x64 assembler are not working as intended, especially not under Linux for some strange reasons.

**Comment by andersmelander** [comment]
Just tried to have a quick go at this but didn't get far as I started by running the blend unit test...
All merge tests fail. Many blend tests fail because the reference implementation calculates alpha while the others force it to 255. Even ignoring that detail there are problems; BlendMemEx_ASM has a problem as you noticed and the MMX BlendTestLine1 test throws an exception (a missing EMMS somewhere).

**Comment by CWBudde** [comment]
As I tried to explain in the #53 it's probably a base question of what we want this library to be in the future. In the past it was written with performance in mind, lacking quality a bit behind. This was good as it was only intended for GUI elements. Especially for animations, there was no need for perfection.

With SSE2 it was possible to improve some of the optimizations while improving the quality at the same time. Still no decision was done about the future, both was welcome.

Nowadays, performance is not much of an issue anymore. If so, one would probably try to perform computations on the GPU anyway.
For high quality algorithms, the simple 8-bit per entity color space isn't enough anymore. Both aspects would render the code in this repository pointless. But it is not, there's still a niche where all this is useful, if only for the ease of use in Delphi.

So in my opinion, we should not spend too much work on getting it right (it will never be right), instead the easiest solution would be to stay on the path between performance and quality. We just need to get the bugs sorted out.

In this very case, it could mean to either find some workaround (e.g. conditional compilation for the purepascal case) or to make this case a risk on your own.

A rewrite will cost time and will possibly cause incompatibilities on the user end. At least for me, neither will be economic enough to make it happen.

**Comment by dtamade** [comment]
I also found this problem. I hope Lazarus can use the optimized assembly code.

**Comment by CWBudde** [comment]
Actually it's not that much of a problem to fix the optimized assembly code. It's just not just one issue, but dozens. It'll need a few days to get everything sorted.

**Comment by andersmelander** [comment]
It's news for me that Graphics32 was only ever intended for GUI stuff but I'm not really interested in that discussion. The fact is that it is used for all kinds of 32-bit image manipulations and presentation and while performance is definitely a key feature that, IMO, is worthless if we can only achieve it at the cost of correctness. Especially in core features such as blend and merge which is used just about everywhere and especially since it's perfectly possible to achieve both performance and correctness. After all it's possible for many other libraries that operates within the same constraints.
I think a first step would to replace the A*B/256 approximation with one that is correct for all values of A and B. This should be fairly easy and should incur no loss of performance: https://godbolt.org/z/rq7fz1qvj

**Comment by CWBudde** [comment]
It was told to me as well, as I never had direct contact with Alex, the original developer. However, the flaw is already present since the very first commit. Both the ASM and MMX section contained the unprecise division. And given the fact that it was already a SIMD design with before SIMD officially was supported by the processor, it was clearly intended.
The precise multiplication was already possible by then, but only at the expense of a single operation per component. With two values calculated in one operation, only half of the precision (16bit) was available.
The code you refer to is just one value per operation, thus 32-bit are available. This means that the precision is better at the expense of half of the performance.

But what I meant: We shouldn't fight to make ancient code work better, that's not going to happen without a trade off as it is already engineered to the max. We should focus on what we want. Since with SSE2 it's possible to maintain full precision, we should just focus on that. It would even make sense to drop the old ASM / MMX and 3DNow! code entirely and just focus on PurePascal and SSE2. Both with the needed precision. The speed will still be good enough.

**Comment by andersmelander** [comment]
> focus on PurePascal and SSE2.

I agree.

**Comment by andersmelander** [comment]
It turned out that this problem had nothing to do with #53.

The problem was a simply omission in the `BlendMemEx_Pas`and `BlendRegEx_Pas` functions.
Instead of calculating the blend as

    ARGB = (M * FA) * FARGB + (1 - (M * FA)) * BARGB

it was calculated as

    ARGB = M * FARGB + (1 - (M * FA)) * BARGB

There was no problem with the corresponding _Asm implementations as I had already fixed those when I updated the unit tests.
