### ISSUE TITLE
Problem regarding new and old location in TRubberbandLayer OnResizing

### ISSUE THREAD

**Issue by pnxtm** [graphics32/graphics32#164]
Hi everyone.
In TRubberbandLayer.OnResizing we have a NewLocation and OldLocation that is set when moving or resizing the RubberBandLayer. The problem is if we don't resize and just move the layer then we have following situation (often):

EqualRectSize(NewLocation, OldLocation) is False

I saw this when the image is scaled (downsized).
I think there might be a miscalculation in GR32_Layers.TRubberbandLayer.MouseMove

**Comment by andersmelander** [comment]
I haven't tried reproducing this problem but I can't spot any problem by looking at the code in `TRubberbandLayer.MouseMove`.
From what I can see, when the layer is just moved the size (width/height) isn't modified at all.

I think what you're seeing is the result of `NewLocation` and `OldLocation` being float rects which makes the calculations being performed on them (and comparisons on them) susceptible to the usual floating point problems<sup>[1](#footnote1)</sup> in which case the problem is actually with `EqualRectSize`. `EqualRectSize` should be modified to include an _Epsilon_ parameter. See `SameValue`in `math.pas.`.

<a name="footnote1">1</a>)

- [Floating point numbers — Sand or dirt](https://web.archive.org/web/20200106152627/http://www.rvelthuis.de/articles/articles-floats.html)
- [What Every Programmer Should Know About Floating-Point Arithmetic](https://floating-point-gui.de/)
- [What Every Computer Scientist Should Know About Floating-Point Arithmetic](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html)

**Comment by pnxtm** [comment]
> I think what you're seeing is the result of NewLocation and OldLocation being float rects which makes the calculations being performed on them (and comparisons on them) susceptible to the usual floating point problems

You mean the calcs in EqualRectSize? 

By the way, why do I see this in non scaled mode? just when I resize the image in ScaleMode<>smNormal

**Comment by andersmelander** [comment]
> You mean the calcs in EqualRectSize?

Yes, that too. I mean that when using floating point, _W = x1 - x2_ does not mean that _(x1+n) - (x2+n) = W_. That's just the way floating point works. Some numbers cannot be expressed exactly. The links I provided explains why.

> why do I see this in non scaled mode?

I have no idea but if I'm right about the cause then it's not really relevant to the problem.

Try modifying `EqualRectSize` in `gr32.pas` like this:

```
interface
...
function EqualRectSize(const R1, R2: TFloatRect; Epsilon: Double = 0): Boolean; overload; {$IFDEF USEINLINING} inline; {$ENDIF}

implementation
...
function EqualRectSize(const R1, R2: TFloatRect; Epsilon: Double): Boolean;
begin
  Result := SameValue(R1.Right - R1.Left, R2.Right - R2.Left, Epsilon) and
    SameValue(R1.Bottom - R1.Top, R2.Bottom - R2.Top, Epsilon);
end;
```

If that doesn't solve the problem then I will need to know what the values of `R1` and `R2` are when `EqualRectSize` returns False but you'd expect it to return True.

**Comment by pnxtm** [comment]
I think you are right. `EqualRectSize` is using `FixedRect` to convert rects and I missed the `Round` func. I used an epsilon like solution like your suggestion to workaround this. I ended up saying this isn't a bug or any problem and about the scaled situation I think this is because of the `Round` function.

Thanks a lot for your time and information.
Regards

**Comment by andersmelander** [comment]
Thanks for the feedback.
Good to hear that you solved it at your end. I still think we should change `EqualRectSize` to include an _Epsilon_ parameter if that can help other people avoid the same problem.
