### ISSUE TITLE
Delphi XE2 error: "$IFEND expected but $ENDIF found"

### ISSUE THREAD

**Issue by zedxxx** [graphics32/graphics32#172]
This block https://github.com/graphics32/graphics32/blob/master/Source/GR32_Compiler.inc#L397 is related to FPC but Delphi also try parse it and fails with error:
```
[DCC Error] GR32_Compiler.inc(397): E2029 $IFEND expected but $ENDIF found
```

**Comment by andersmelander** [comment]
I don't have XE2 installed anymore so i can't reproduce but I think I can see why it's choking on it. In order to locate the end of the `{$IFDEF COMPILERFPC}` block (so it can ignore it) it needs to be able to parse the structure of the stuff inside the block so it still need to be valid from XE2's POW. Therefore `$IF` must be terminated with `$IFEND`.

Try replacing the `{$ENDIF}` in line 397 with `{$IFEND}`. AFAIK FPC also supports that syntax so it shouldn't break FPC support.

**Comment by zedxxx** [comment]
Yes, `{$IFEND}` fix issue.
