### ISSUE TITLE
Problem with BitmapFileHeader data on newer versions of GR32.pas 

### ISSUE THREAD

**Issue by UKobsa** [graphics32/graphics32#173]
On 11.10.2020  a change was added where it changed the definition of BitmapFileHeader structure. Especially SaveToStream has changed too:

```
procedure TCustomBitmap32.SaveToStream(Stream: TStream; SaveTopDown: Boolean = False);
﻿...
begin
  ...
  FileHeader.bfType := $4D42; // Magic bytes for Windows Bitmap
  FileHeader.bfSize := BitmapSize + SizeOf(TBitmapFileHeader) + SizeOf(TBitmapInfoHeader); // Size of file
  FileHeader.bfReserved1 := $5247; // Actual value doesn't matter.  <-- WHY
  FileHeader.bfReserved2 := $3233; //   -                           <-- WHY
  ...
end;

```
So what are those values set for bfReserved1/2. According to [https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapfileheader]( https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapfileheader )
the﻿y must be zero. Indeed I have a problem that a library for PDF handling assumes that they are zero and fails to save an bitmap to PDF therefore.

Is i﻿t save to set those two parameters back to zero or are there any other dependencies.

kind regards,
Ulrich

**Comment by andersmelander** [comment]
The values are only there so we can identify bitmaps created with Graphics32; If you view the saved bitmap in a hex viewer your will see that the field values produce the string GR32 in the header. This is the only purpose.

Microsoft themselves (i.e. Windows and Microsoft's tools and applications) does not validate the fields and others shouldn't either. Because while it is documented that we _must_ set the value to zero (yes, we break this rule), it isn't documented that it _will_ always be zero. The fields are _reserved_ so it is up to Microsoft to decide what goes into the fields. Of course we know that Microsoft will not change the meaning of these fields almost 40 years after they were defined, but that doesn't change the fact that it's wrong for a BMP reader to expect (and require) the fields to be zero.

That said, since there's no _good_ reason for us to put anything other than the required zero into the field, and it apparently cause problems if we don't, we should zero the fields.

**Comment by UKobsa** [comment]
I guess, the original owner of that PDF library tried to use the reserved fields to better identify a stream of data as an BMP. To do so, they load the beginning of the stream on a TBitmapFileHeader structure and check if type is "BM" as well as the reserved bytes are zero. That's slightly more error prove then just look on the first two bytes. So I think both sides have their point. 
But I would also prefer to have that fields set to zero.
