### ISSUE TITLE
Fastest line drawing?

### ISSUE THREAD

**Issue by Stefan311** [graphics32/graphics32#177]
Hi,

I have a Delphi application who draws multiple curves on multiple screens. Something like this:
`Form1.Canvas.MoveTo(0,data[0]);
for i:=1 to Form1.Width do Form1.Canvas.LineTo(i,data[i]);`

This runs well for several years now, but recently I got much higher CPU load while doing so (>100% which is bad). I suspect Microsoft changed something in there GDI code in one of the last windows updates.

One idea to get out of this situation is to use graphics32, but on a quick performance comparison test i see no difference between Form.canvas and Image32.canvas. Do I use graphics32 right?

Can you hint me to the most performant use of graphics32 for this case?

Greetings
Stefan

**Comment by andersmelander** [comment]
First of all you _should_ profile your code to determine what the actual bottleneck is. Graphics32 is generally **much** faster than GDI and if you're not seeing any improvement then the bottleneck is probably something else or your using Graphics32 wrong.

The following demonstrates the performance difference between `TBitmap.Canvas`, `TBitmap32` and `TBitmap32.Canvas`:
![billede](https://user-images.githubusercontent.com/18141921/152692373-1b7fb212-584a-4cfe-a975-d654f39d8cd5.png)
[CanvasLineToBenchmark.zip](https://github.com/graphics32/graphics32/files/8010709/CanvasLineToBenchmark.zip)

The lesson here is to use `TBitmap32.LineTo` instead of `TBitmap32.Canvas.LineTo`. The reason is that `TBitmap32.Canvas` is just a GDI wrapper around `TBitmap32`'s internal bitmap so `TBitmap32.Canvas.LineTo` will use the GDI line functions (slow) while `TBitmap32.LineTo` will use the Graphics32 line functions (fast).

Generally, unless you know what you're doing, you shouldn't draw onto a control's canvas like you do. The exception is `TPaintBox` which is meant to be drawn upon.

**Comment by Stefan311** [comment]
Many thanks!

> The lesson here is to use TBitmap32.LineTo instead of TBitmap32.Canvas.LineTo
Yea, that's exactly the information I needed. It is also handy to have a benchmark example application. 
Here I see a weakness of TBitmap32.LineTo: it cannot draw line width greater than one. I modified the benchmark example to to draw 4 lines 1 pixel apart, and it still outperforms the canvas methods with 2 pixel wide lines by far. So: great job!

Why I shouldn't draw into a control? It is in the FormPaint method, who is described to be for that.

One more question: is it allowed to mix TBitmap32.* and TBitmap32.Canvas.* functions, so I can use the advantages of both?

**Comment by andersmelander** [comment]
> Here I see a weakness of TBitmap32.LineTo: it cannot draw line width greater than one.

Use the Polyline functions in GR32_Polygons instead.
This is from the Drawing\Polygons example:
![billede](https://user-images.githubusercontent.com/18141921/152703256-ecf231a2-dedb-482e-a9c1-0bc2910d50d9.png)

> Why I shouldn't draw into a control? It is in the FormPaint method, who is described to be for that.

Ah yes. That's another exception.
The reason why one usually doesn't want to draw on a control canvas is that whatever one draw is overwritten by the control when it redraws itself. In most cases it's better to draw onto a bitmap (once) and then draw this bitmap onto the control canvas each time it needs to be redrawn.

> is it allowed to mix TBitmap32.* and TBitmap32.Canvas.* functions

Yes. Both draw onto the same internal bitmap.

**Comment by Stefan311** [comment]
I finished to convert my application to graphics32 with a huge performace gain!
So big thanks for developing and providing graphics32.

![Untitled](https://user-images.githubusercontent.com/42878056/155529918-1a7d7103-d626-4656-968f-c2fa4d0daca3.png)

I don't use GR32_Polygons because it would be too much to change in my code, I duplicated and modified the GR32:LineS procedure insead. Very handy to having the source code of libaries.
