### ISSUE TITLE
TPaintBox32.Buffer.Line not correct?

### ISSUE THREAD

**Issue by artelogic-com** [graphics32/graphics32#188]
pb1's size is 200x100

  pb1.Buffer.FillRect(0,0,pb1.Buffer.Width-1,pb1.Buffer.Height-1,TColor32($FFFFFF00));
  pb1.Buffer.Line(0,0,pb1.Buffer.Width-1,pb1.Buffer.Height-1,TColor32($FF00FFFF),False);

and

  pb1.Buffer.SaveToFile('SavedToFile.bmp');  (seems to be always +40 in both directions)

brings out this (see attached files):
[Paintbox32.zip](https://github.com/graphics32/graphics32/files/8777324/Paintbox32.zip)

**Comment by artelogic-com** [comment]
Ok, I see, there is a BufferOversize (which is 40). But this can't be the purpose of it.

**Comment by andersmelander** [comment]
I don't think there's a problem here.
`TPaintBox32.BufferOverSize` is used to avoid the buffer being reallocated every time the control is resized. The default value of 40 allows the height/width of the control to be changed up to 40 pixels before the buffer is reallocated. I think it's even documented. Let me check... Yes, here it is: [`TCustomPaintBox32.BufferOverSize`](https://graphics32.github.io/Docs/Units/GR32_Image/Classes/TCustomPaintBox32/Properties/BufferOversize.htm)

If you need to save the buffer, as you seem to be doing, then you should set it to zero - or maybe use a `TImage32` instead.

With regard to the colors; On my system (Windows) the screenshot shows yellow line on aqua background while the saved bit has an aqua line on a yellow background. Is that what you're seeing too?

By the way, your FillRect isn't covering the whole bitmap; The right column and bottom row is transparent (i.e. not filled).
The reason is that the coordinates specify the top/left corner of the pixels so width=X2-X1 and height=Y2-Y1. A bit confusing but at least it's the same in other libraries. Here's the documentation: [`TCustomBitmap32.FillRect`](https://graphics32.github.io/Docs/Units/GR32/Classes/TCustomBitmap32/Methods/FillRect.htm)

**Comment by artelogic-com** [comment]
> With regard to the colors; On my system (Windows) the screenshot shows yellow line on aqua background while the saved bit has an aqua line on a yellow background. Is that what you're seeing too?

Yes.
