### ISSUE TITLE
Issue about clipper.

### ISSUE THREAD

**Issue by achinastone** [graphics32/graphics32#211]
I tested **TClipper**, and have some doubt.
The following is pseudocode.

Clipper.AddPaths([(0.0), (0.1), (1, 1), (1,0)], ptSubject);
Clipper.AddPath([(0,1), (1,1), (1,2), (0,2)], ptClip);
Clipper.Execute(ctUnion, frNonZero, Paths);
The **Paths** has 6 points = [(0, 0), (1,0), (1,1), (1,2), (0.2), (0,1)]   (_I think the result is not bad_)

BUT
Clipper.AddPaths([(0.0), (0.1), (1, 1), (1,0)], ptSubject);
Clipper.AddPath([(1,0), (2,0), (2,1), (1,2)], ptClip);
Clipper.Execute(ctUnion, frNonZero, Paths);
The **Paths** has 2 region:
   points[0] = [(1,0), (2,0), (2,1), (1,2)] 
   points[1] = [(0,0), (1,0), (1,1), (0,1)] 
If i using the path as polygon to draw path region.  There will be a line in the middle of the two areas. What should I do to make this line disappear

**Comment by andersmelander** [comment]
Reproduced

**Comment by andersmelander** [comment]
I don't know the inner workings of clipper so rather than trying to fix this issue in the old GR32_Clipper (based on Clipper1) it would probably be safer if Graphics32 was updated to use the new [Clipper2](https://github.com/AngusJohnson/Clipper2) instead since that is actively maintained

Maybe @AngusJohnson has an idea about how big a task that would be...?

**Comment by achinastone** [comment]
> I don't know the inner workings of clipper so rather than trying to fix this issue in the old GR32_Clipper (based on Clipper1) it would probably be safer if Graphics32 was updated to use the new [Clipper2](https://github.com/AngusJohnson/Clipper2) instead since that is actively maintained
> 
> Maybe @AngusJohnson has an idea about how big a task that would be...?

I tested the Clipper2. The results are similar. However, vertical regions are not merged.

**Comment by andersmelander** [comment]
Ah, yes. I've looked through [the issues related to "union" on Clipper2](https://github.com/AngusJohnson/Clipper2/issues?q=is%3Aissue+is%3Aclosed+union) and unfortunately it appears this is "as designed".
http://www.angusj.com/clipper2/Docs/Overview.htm#simplify

**Comment by AngusJohnson** [comment]
> I tested the Clipper2. The results are similar. However, vertical regions are not merged.

The issue here is related to scale and misunderstanding the implications of rounding. Both Clipper1 & Clipper2 perform boolean operations using integer coordinates to avoid problems of numerical robustness. So it's inappropriate to use coordinates with these very small integer values, and doing so will  almost guarantee unexpected solutions. If you scale the subject and clip paths by a factor of 10, you should get the expected result.  

When I get a moment I'll have a look at Gr32_Clipper.pas and see why coordinate scaling isn't being applied.

**Comment by AngusJohnson** [comment]
> I'd rather you used a few moments to evaluate the effort required to migrate to Clipper2.

[Gr32_Clipper2.zip](https://github.com/graphics32/graphics32/files/9957185/Gr32_Clipper2.zip)

**Comment by andersmelander** [comment]
Holy cow! That was fast. Much appreciated.

I'll need some time to investigate the differences between Clipper1 and Clipper2 (they seem to be barely related). I think what I'll try first is to keep your GR32_Clipper2 unit as-is and then rewrite the old GR32_Clipper unit to more or less just wrap the functions in GR32_Clipper2 where possible. This should provide as much backward compatibility as possible.
I'll worry about performance later.

Again, thanks a bunch.

**Comment by AngusJohnson** [comment]
> @AngusJohnson I noticed that Clipper2 doesn't seem to support the [jtRoundedEx](https://github.com/graphics32/graphics32/issues/47) join type. Is that because Clipper2 doesn't need it or did you simply decide not to implement it?

It's the latter. IMHO it unnecessarily complicates the code and would rarely be useful. For example with a CNC milling machine, whenever the milling bit turn a sharp angle the inner angle is always sharp, not rounded. And inner rounding would be detrimental as it extends the cut beyond the offset distance.
