### ISSUE TITLE
Cant' install in Lazarus/MacOS

### ISSUE THREAD

**Issue by grogcw** [graphics32/graphics32#217]
Hi !

I'm running Lazarus (2.2.4) on Big Sur (11.7.1) and I followed the installation instructions for [lazarus](https://graphics32.github.io/Docs/Installation.htm) but I get an error at install/compile time from git cloned sources :

`GR32.pas(7056,13) Error : Identifier not found "TLCLBackend"`

What did I do wrong or what am I missing ?

Thanks for taking care,

Cheers !

**Comment by andersmelander** [comment]
My guess is that you're using a front-end/widget-set that isn't supported.

The following block in gr32.pas is used to include the FPC backend:

```
  {$IFDEF LCLWin32}
    GR32_Backends_LCL_Win,
  {$ENDIF}
  {$IF defined(LCLGtk) or defined(LCLGtk2)}
    GR32_Backends_LCL_Gtk,
  {$IFEND}
  {$IFDEF LCLCarbon}
    GR32_Backends_LCL_Carbon,
  {$ENDIF}
  {$IFDEF LCLCustomDrawn}
    GR32_Backends_LCL_CustomDrawn,
  {$ENDIF}
```

So if none of the above are defined then the `TLCLBackend` type will not be declared.

**Comment by grogcw** [comment]
I'm not trying anything but to install the package, that's were the problem occurs.

Is there anything to declare beforehand ?

**Comment by andersmelander** [comment]
No, you shouldn't have to define anything beforehand.

One of the symbols `LCLWin32`, `LCLGtk`, `LCLGtk2`, `LCLCarbon`, or `LCLCustomDrawn` must be defined but I believe the IDE should do that for you based on what platform (Windows/Linux/MacOS) and UI interface you're using. I'm afraid I can't be more specific than that since I'm not using Lazarus.

My guess is that you're using the Cocoa interface and as far as I know, no one has written a Graphics32 backend for that (see #100). You could try asking on the Lazarus forum if anyone there has done it.

**Comment by grogcw** [comment]
Thanks for your support !
