### ISSUE TITLE
Text quality is poor on transparent buffer

### ISSUE THREAD

**Issue by thachngopl** [graphics32/graphics32#23]
Hi,

As the title. Drop a paintbox32 into form. Here is the code for PaintBuffer event:
``` pascal
var
  TextBuffer: TBitmap32;
begin
  PaintBox321.Buffer.Clear(Color32(clBtnFace));

  TextBuffer := TBitmap32.Create;
  TextBuffer.SetSize(100, 100);
  TextBuffer.DrawMode := dmTransparent;
  TextBuffer.CombineMode := cmBlend;
  TextBuffer.Clear(0);

  TextBuffer.Font.Color := clRed;
  TextBuffer.Textout(0, 0, 'TEST STRING');

  TextBuffer.RenderText(0, 30, 'TEST STRING', 4, clRed32);

  TextBuffer.Canvas.Font.Color := clRed;
  TextBuffer.Canvas.Brush.Style := bsClear;
  TextBuffer.Canvas.TextOut(0, 60, 'TEST STRING');

  TextBuffer.DrawTo(PaintBox321.Buffer, 0, 0);

  TextBuffer.Free;

end;

```

Result:

![capture](https://user-images.githubusercontent.com/16706272/28400074-15f7bfba-6d3b-11e7-98fc-9466fcff2fb1.PNG)

Expectation:

![capture](https://user-images.githubusercontent.com/16706272/28400095-2fdc64d0-6d3b-11e7-938e-52d617866e88.PNG)

Tried for other DrawMode & CombineMode. No success.

**Comment by CWBudde** [comment]
In order to make it work you should use dmBlend as blend mode. Without it does not use blending, but masking (dmTransparent) or copying (dmOpaque). Both do not consider the CombineMode and will obviously fail.

However, if you use dmBlend you can't directly use the TextOut method anymore as it doesn't modify the alpha value. And without it is set to 0 (since all alpha values were set to zero by TextBuffer.Clear(0);).

Still, with dmBlend the RenderText doesn't look as perfect as you wish. This comes from the fact that implicit blending occurs once with the black, transparent color as soon as you call RenderText().

As far as I can see, you can only avoid this if you clear the TextBuffer with the same (but transparent) color, which you use for drawing. For example, if you want to draw with clRed32 you should clear the TextBuffer with something like this:

    TextBuffer.Clear($00FF0000);

Alternatively you could fill a transparent rect in that color to avoid this or write your own RenderText function.

Or you could render text transparently directly onto the paintbox. Or you could us the vector drawing from the latest source code, which should not be affected by this.

**Comment by CWBudde** [comment]
Here is the code which is needed to use the vector text drawing in GR32:

```
var
  Intf: ITextToPathSupport;
  Path: TFlattenedPath;


    Path := TFlattenedPath.Create;
    try
      if Supports(TextBuffer.Backend, ITextToPathSupport, Intf) then
      begin
        Intf.TextToPath(Path, 0, 60, 'TEST STRING');
        PolyPolygonFS(TextBuffer, Path.Path, clRed32);
      end;
    finally
      Path.Free;
    end;

```

Still the same problems happen as the call to PolyPolygon blends the font color (red) onto the transparent black.

**Comment by CWBudde** [comment]
With the vector renderer it will only get correct when you change TextBuffer.CombineMode to cmMerge.

**Comment by thachngopl** [comment]
It works. Thank you very much :)
