### ISSUE TITLE
ComObj

### ISSUE THREAD

**Issue by PeterPanino** [graphics32/graphics32#233]
The Delphi 11 Package uses the wrong namespace in the uses clause of the Package: It should be **System.Win.ComObj** instead of **ComObj**.

**Comment by TommiPrami** [comment]
Depends on the Delphi version. I think Graphics32 still supports older Delphi versions which did not support Unit Scopes/Name spaces.

**Comment by PeterPanino** [comment]
But it's the Package for Delphi **11**! People with older Delphi versions will not install the Delphi 11 Package.

**Comment by andersmelander** [comment]
> I think Graphics32 still supports older Delphi versions

The oldest supported version is currently XE2, but unfortunately, the names of some units are different on FPC so as much as I want to I can't just change all unit names to use the fully scoped names.

> People with older Delphi versions will not install the Delphi 11 Package.

Sure they will; You just need to add `System.Win` to the **Unit scope names** package project setting.
I'm assuming that it is the run-time package you're having problems with because I can see that the design-time package already has `System.Win` in the unit scope.

**Comment by veftodii** [comment]
So, what do you think is the best way to do it? I added this unit scope name on my PC, but I will need to let others know about this too. We are a team of 6 developers so this is a quick solution for now.
Can you add this change to the project settings only for the Delphi 11 packages? In this way, the .pas files will be untouched as they are shared between packages for different Delphi versions.

**Comment by andersmelander** [comment]
> Can you add this change to the project settings only for the Delphi 11 packages?

Yes, that's where it's done.

Or were you asking if _I_ would do it? In that case: Not right now; I'm too busy. If you can create a pull request with just this change, I'll merge it in.

**Comment by veftodii** [comment]
Yes, I asked about the second option. OK. I will create a pull request and just add "System.Win" in the project file as text if this is possible to add only on one line. I will check this first.

**Comment by veftodii** [comment]
I created a pull request. Only one text line was updated.
