### ISSUE TITLE
TScreenColorPickerForm does not work

### ISSUE THREAD

**Issue by PeterPanino** [graphics32/graphics32#234]
In the example: **\Examples\General\Image32**, the creation of the FScreenColorPickerForm does not work as intended:

`FScreenColorPickerForm := TScreenColorPickerForm.Create(Application);`

It creates only a **WHITE** screen which I suppose should be transparent!

**Comment by PeterPanino** [comment]
Ideas for the screen color picker:

1. Get a real-time preview of a specified area around the mouse cursor
2. Optionally, get the average color of a specified area around the mouse cursor

**Comment by andersmelander** [comment]
Good ideas but I think they are better suited for an example application. I'll put something together.

> Get a real-time preview of a specified area around the mouse cursor

I'm assuming you mean a zoomed view? Otherwise, just look at the screen :-)

> get the average color of a specified area

I'm not sure how useful that would be. I mean in which colorspace do you compute the average? A simple RGB average isn't really that meaningful.
What is the use case?

**Comment by PeterPanino** [comment]
> What is the use case?

A user asked me that.
