### ISSUE TITLE
Rasterize SVG image

### ISSUE THREAD

**Issue by PeterPanino** [graphics32/graphics32#235]
Rasterizing an SVG image (to a specified size) would be a nice feature.

**Comment by andersmelander** [comment]
It sure would. Pull requests are welcome :-)

I've considered integrating the SVG functionality from the Image32 library into Graphics32 but unfortunately, it's pretty tightly bound to the rest of that library.

However, since both libraries basically just operate on a block of memory (the bitmap memory) and Graphics32's `TBitmap32` allows you to specify the backend (the source of the memory block), one should be able to wrap a `TBitmap32` around a `TImage32` of the Image32 library.
