### ISSUE TITLE
GetIt

### ISSUE THREAD

**Issue by mgcd-jed** [graphics32/graphics32#251]
Hi,

Would it be possible to publish this on GetIt ? I searched and didn't find it there.
I don't know what's the intended way of consuming this library ; do I `git clone` and using release tags to update ?

**Comment by andersmelander** [comment]
I don't know the procedure for getting it included in GetIt and I don't really have time to investigate it.

If you're already using Git then you can make a local clone and install one of the packages in `Source\Packages`. Otherwise, just download the zip with the latest source:
![billede](https://user-images.githubusercontent.com/18141921/234601014-cbefd4a6-5ba0-4196-8358-6fb34b360147.png)

It's best if you can use Git since that makes it so much easier to update later on - and follow what's going on with the library.

**Comment by mgcd-jed** [comment]
I'm not sure what I'm supposed to do to install this, it's just a regular Delphi project ? Do I need to compile it to a .bpl file myself ? If so, how and which one should I compile (I'm guessing GR32_R, but what's the difference between the two ?)

I've tried compiling the D103/GR32_R project using Rio 10.3, but while it works in the Debug config in Release I get this error :
```
[Fatal Error] Can't load package GR32_RD10.bpl.
The system cannot find the file specified
```

Compiling GR32_D leads to the same error with `GR32_DD10.bpl`.

This is quite weird since the files do get created, but under the name `GR32_RD103`.bpl.

**Comment by andersmelander** [comment]
> The errors below still happened, but it works anyway so...

The package files are probably misconfigured. I'll have a look at them.

The installation procedure is mentioned in the documentation but unfortunately, that section hasn't been updated since XE2 so it's pretty outdated.

**Comment by andersmelander** [comment]
Delphi 10.x and 11.x packages has been fixed.
The Delphi 10.3 packages are now named `GR32_R260.bpl` and `GR32_D260.bpl`. This is the same naming scheme used by Delphi.

If you update to use these new packages you will need to uninstall the old design-time package before you compile and install the new ones (_Component -> Install packages -> Remove_).
