### ISSUE TITLE
TBitmap32 can no longer be assigned to TPicture

### ISSUE THREAD

**Issue by fsiek** [graphics32/graphics32#261]
```
  LBitmap := TBitmap32.Create(100,100);
  try
    Image1.Picture.Assign(LBitmap);
  finally
    LBitmap.Free;
  end;
```
Leads to EConvertError "TBitmap32 can not be assigned to TPicture". With Github version from 13. July 2022 the code works fine.
I guess it has something to do with the new ImageFormatManager that supports TBitmap but not TBitmap32. As a workaround I assign the TBitmap32 to a TBitmap first an then assign the TBitmap to TPicture.

**Comment by andersmelander** [comment]
Direct `TBitmap32` <-> `TPicture` conversion now requires that you include the `GR32.ImageFormats.TPicture` unit in your uses clause.

The reason the conversion isn't enabled by default is that it's relatively rare and thus often just an unnecessary dependency.

FWIW, `TPicture` already has an internal `TBitmap` so you don't need to create a temporary one. You can just assign `TBitmap32` to `TPicture.Bitmap` directly.

**Comment by fsiek** [comment]
Sorry but even if I included GR32.ImageFormats.TPicture, it does not change anything.

**Comment by andersmelander** [comment]
Yes, you are right.

The bug is that the assignment only works if `TPicture.Graphic` is assigned (i.e. the `TImage` already contains an image).
You can work around it by forcing the `TPicture` to create the internal bitmap before you do the assignment: 

```delphi
  LBitmap := TBitmap32.Create(100,100);
  try
    Image1.Picture.Bitmap;
    Image1.Picture.Assign(LBitmap);
  finally
    LBitmap.Free;
  end;
```

The fix I will implement will assign to `TPicture.Graphic` if it is <> nil, otherwise I will assign to `TPicture.Bitmap`.

**Comment by fsiek** [comment]
Thanks for fixing it so quickly.
