### ISSUE TITLE
GR32_Lazarus: No matching implementation for interface method

### ISSUE THREAD

**Issue by faludiz** [graphics32/graphics32#270]
On compile the package i got this error message:

```
Compile package GR32_Lazarus 2.0: Exit code 1, Errors: 1
GR32_Backends_LCL_Gtk.pas(55,17) Error: No matching implementation for interface method "InvalidateRect(TWinControl;const TRect);" found
```

OS: Ubuntu 22.04.3 LTS
Lazarus: 2.2.6
FPC: 3.2.2

**Comment by andersmelander** [comment]
This is a known problem. See #202 and [this comment](https://github.com/graphics32/graphics32/pull/201#issuecomment-1217164438).

The problem is that I don't have a system with GTK on it and no one has volunteered to implement `IUpdateRectSupport` in `GR32_Backends_LCL_Gtk`. So basically only `GR32_Backends_LCL_Win` (and maybe `GR32_Backends_LCL_CustomDrawn`) works with FPC at the moment.

**Comment by CuriousKit** [comment]
Confirmed the bug on aarch64-linux.  Let me see if I can find and solve anything.  My desire is to get Graphics32 to work on Arm-64 processors (e.g. Raspberry Pi, which uses a Linux-based OS) so we have a common goal.

**Comment by andersmelander** [comment]
Thanks. Please give the **FPC_GTK** branch a try.

**Comment by CuriousKit** [comment]
Oh sweet!  I just updated my trunk a few hours ago... now to give it a try!
