### ISSUE TITLE
No Package for Delphi 12?

### ISSUE THREAD

**Issue by PeterPanino** [graphics32/graphics32#273]
Is there a package for Delphi 12?

**Comment by andersmelander** [comment]
You should be able to use the Delphi 11.x package as-is; It's configured to be version independent.

I haven't done any serious testing with Delphi 12 because of the compiler bugs:
- [Arithmetic operations on record fields return incorrect results in certain cases if the "Optimization" compiler option is enabled](https://quality.embarcadero.com/browse/RSP-43274)
- [Wrong Delphi code optimization for integer div/mod](https://quality.embarcadero.com/browse/RSP-43418)

Reopen the issue if the Delphi 11.x package doesn't work for you.

**Comment by PeterPanino** [comment]
You are right; the Delphi 11 Package can be compiled in Delphi 12.
