### ISSUE TITLE
Rename integrated Clipper units to avoid name/version conflicts

### ISSUE THREAD

**Issue by zedxxx** [graphics32/graphics32#279]
Conflicts are possible in the following cases:
- the application simultaneously uses Clipper v1 (unit name Clipper.pas) and GR32, which uses Clipper v2 (unit with the same name Clipper.pas);
- the application uses Clipper v2, but a newer or older revision than the one used in GR32.

I propose to rename the Clipper units as follows:

GR32.Clipper.inc
GR32.Clipper.pas
GR32.Clipper.Core.pas
GR32.Clipper.Engine.pas
GR32.Clipper.Minkowski.pas
GR32.Clipper.Offset.pas
GR32.Clipper.RectClip.pas

**Comment by andersmelander** [comment]
Renaming the clipper units in Graphics32 will only produce even worse problems for applications that otherwise use Clipper2.

There is no conflict for projects that have multiple uses of a library as long as the project is correctly configured; The solution is simply to set up the unit search path so the preferred version is first in the path.

Renaming the Clipper2 unit would also make it harder for Graphics32 to track and keep up with the Clipper2 repository.

I suggest you instead rename your old copy of Clipper1.

**Comment by zedxxx** [comment]
> The solution is simply to set up the unit search path so the preferred version is first in the path.

It does not help if my application requires Clipper2 ver. 1.3.0 but GR32 needs Clipper2 ver. 1.1.0 or vice versa.

> Renaming the Clipper2 unit would also make it harder for Graphics32 to track and keep up with the Clipper2 repository.

This task can be automated with some script.

**Comment by andersmelander** [comment]
> It does not help if my application requires Clipper2 ver. 1.3.0 but GR32 needs Clipper2 ver. 1.1.0 or vice versa.

Graphics32 doesn't require a specific version of Clipper2. If your application require a specific version then place that version before Graphics32 in your search path.
