### ISSUE TITLE
Bug with layes visibility change

### ISSUE THREAD

**Issue by zedxxx** [graphics32/graphics32#309]
Changing the `Visible` property does not always work correctly.

https://github.com/graphics32/graphics32/assets/6298130/3fa94a23-7459-4514-a6d4-768cef102376

Test project: [VisibleTest.zip](https://github.com/graphics32/graphics32/files/15051967/VisibleTest.zip)

Expected behavior: Layers should show or hide without having to click on the force refresh button.

P.S. Changing [this line](https://github.com/graphics32/graphics32/blob/master/Source/GR32_Layers.pas#L1317) to `if Visible or ForceUpdate then ...` fix bug for TPositionedLayer. 

Maybe there are some forgotten `Visible or ForceUpdate` conditions somewhere?

**Comment by andersmelander** [comment]
Reproduced

**Comment by andersmelander** [comment]
For `TPositionedLayer` I agree with your proposed fix.

But apart from that the way you are using the layers is not correct.

Generally, drawing on the buffer in the `OnPaint` is fine, but since you are drawing outside the area covered by the layer (you haven't set the size/position of the `TBitmapLayer`) it is your own responsibility to invalidate the area you are drawing on when the layer visibility changes. The `TImage32` control has no way of knowing that you are drawing stuff outside the area covered by the layer.

For a `TPositionedLayer` you would paint on the buffer _inside the area covered by the layer_. So your OnPaint handler should look something like this:
```delphi
procedure TMainForm.OnPositionedLayerPaint(Sender: TObject; Buffer: TBitmap32);
begin
  var r := TPositionedLayer(Sender).GetAdjustedLocation;
  Buffer.Textout(Round(r.Left), Round(r.Top), 'Positioned Layer ' + FCount.ToString);
end;
```

For a `TBitmapLayer` you would normally _modify the layer bitmap and then let the layer repaint itself automatically_. If you draw on the layer bitmap in the OnPaint event then the change will only become visible the next time the layer is repainted since the layer Paint method, unfortunately, is called right before the OnPaint event is fired. I'd really like to change that but it has been this way since 2004 so there would be high risk of breaking peoples code with such a change.
Anyway, set the layer location and the size of the bitmap:
```delphi
  FBitmapLayer := TBitmapLayer.Create(imgMain.Layers);
  var r := FPositionedLayer.Location;
  OffsetRect(r, 0, r.Height);
  FBitmapLayer.Location := r;
  FBitmapLayer.Bitmap.SetSize(Round(r.Width), Round(r.Height));
  FBitmapLayer.Bitmap.Clear(clLime32);
  ...
```
and paint inside the area covered by the layer:
```delphi
procedure TMainForm.OnBitmapLayerPaint(Sender: TObject; Buffer: TBitmap32);
begin
  var r := TBitmapLayer(Sender).GetAdjustedLocation;
  Buffer.Textout(Round(r.Left), Round(r.Top), 'Bitmap Layer ' + FCount.ToString);
end;
```

For `TCustomLayer` _you need to manage the area invalidation yourself_ since the layer class doesn't know anything about how or where you are drawing the layer content.

**Comment by zedxxx** [comment]
By the way, before your last commit with the ForceUpdate fix, this code worked as expected, but now it does not.
```delphi
procedure TMainForm.OnLayerPaint(Sender: TObject; Buffer: TBitmap32);
begin
  Buffer.HorzLineS(0, 175, imgMain.Width, clRed32);
end;
```
So I'm looking for a way to get it working again...

**Comment by andersmelander** [comment]
It really depends on what you are doing with the layer. Can you explain what the layer is for?

**Comment by andersmelander** [comment]
> before your last commit with the ForceUpdate fix, this code worked as expected, but now it does not.

What kind of layer is that?

**Comment by zedxxx** [comment]
TCustomLayer

**Comment by andersmelander** [comment]
Okay and when you say that it doesn't work _as expected_, what do you mean by that (I don't know what you are expecting/experiencing)?

**Comment by zedxxx** [comment]
Sorry, my mistake, it didn't work before.

My question is: how can I make this function to work with TCustomLayer? Is it possible without calling TImage32.Changed?

```delphi
procedure TMainForm.OnCustomLayerPaint(Sender: TObject; Buffer: TBitmap32);
begin
  Buffer.BeginUpdate;
  try
    Buffer.Textout(10, 150, 'Custom Layer ' + FCount.ToString);
    Buffer.HorzLineS(0, 175, imgMain.Width, clRed32);
  finally
    Buffer.EndUpdate;
  end;
end;
```

**Comment by andersmelander** [comment]
I need to know:
> when you say that it doesn't work as expected, what do you mean by that

**Comment by zedxxx** [comment]
It should hide when Layer.Visible = False and show when Layer.Visible = True (when I click on CheckBox in my example).

**Comment by andersmelander** [comment]
Since the `TImage32` control has no idea where on the buffer the layer has painted you will either have to invalidate the whole buffer or the just the area you painted on. You must do this from outside the layer; E.g. the place where you show or hide the layer.

So use `TImage32.Invalidate` or `TImage32.Invalidate(TRect)`

**Comment by zedxxx** [comment]
OK, I got it. Thank you very much!

**Comment by zedxxx** [comment]
It seems that I can use `OnAreaChanged` event to get proper TRect and invalidate TImage32:
```delphi
procedure TMainForm.OnCustomLayerPaint(Sender: TObject; Buffer: TBitmap32);
begin
  Buffer.OnAreaChanged := Self.OnCustomLayerAreaChange;
  Buffer.BeginUpdate;
  try
    Buffer.Textout(10, 150, 'Custom Layer ' + FCount.ToString);
    Buffer.HorzLineS(0, 175, imgMain.Width, clRed32);
  finally
    Buffer.EndUpdate;
  end;
end;

procedure TMainForm.OnCustomLayerAreaChange(Sender: TObject; const Area: TRect; const Info: Cardinal);
begin
  imgMain.Invalidate(Area);
end;
```
