### ISSUE TITLE
Repaint TCustomLayer and draw TBitmapLayer at the same time 

### ISSUE THREAD

**Issue by zedxxx** [graphics32/graphics32#311]
I have a problem with an application that mixes two ways of drawing layers at the same time: for TCustomLayer used event-driven way, for TBitmapLayer direct drawing:

```delphi
begin
  FCustomLayer.Changed; // send message to winapi
  FBitmapLayer.Bitmap.Clear(SetAlpha(clLightGreen32, 100)); // start drawing immediately
end;
```
https://github.com/graphics32/graphics32/assets/6298130/9bf69b82-ab82-48ee-b6d3-32aaf27eb6e4

Test app: [CustomLayerTest.zip](https://github.com/graphics32/graphics32/files/15067367/CustomLayerTest.zip)

P.S. The test application works correctly on the [release/2.0](https://github.com/graphics32/graphics32/tree/release/2.0) branch.

**Comment by andersmelander** [comment]
> P.S. The test application works correctly on the [release/2.0](https://github.com/graphics32/graphics32/tree/release/2.0) branch.

The repaint mechanism was pretty broken in earlier versions so my guess is that it just repainted everything every time something changed. Now it works as designed but unfortunately that also means that a lot of code that did things incorrectly no longer work as it did before.

Anyway, as I explained earlier, `TCustomLayer.Changed` does nothing. The layers doesn't know which area it should invalidate. Only you know that.

Do like this instead (I changed the event to `MouseMove` instead of `MouseDown` just so there's more action):

```delphi
procedure TMainForm.imgMainMouseMove(Sender: TObject; Shift: TShiftState; X, Y: Integer; Layer: TCustomLayer);

  procedure InvalidateCross(const p: TPoint);
  begin
    // Vertical
    imgMain.Invalidate(Rect(p.x, 0, p.x+1, imgMain.Buffer.Height));
    // Horizontal
    imgMain.Invalidate(Rect(0, p.y, imgMain.Buffer.Width, p.y+1));
  end;

begin
  // Invalidate old position so it gets erased
  InvalidateCross(FCurrent);

  FCurrent := Point(X, Y);

  // Invalidate new position so it gets drawn
  InvalidateCross(FCurrent);
end;
```

If you want to see what get's invalidated and repainted, define `UPDATERECT_DEBUGDRAW` in GR32_Image.pas
There are some similar options for the repaint optimizer in GR32_MicroTiles.pas

You might also want to look at the examples in `Examples\General\Optimized repaint`

**Comment by zedxxx** [comment]
In the real application, it is not so easy to manually invalidate everything. It would be great if the library took care of everything itself, as before. Now I will probably have to use `Invalidate` without specifying a TRect.

**Comment by andersmelander** [comment]
> Now I will probably have to use Invalidate without specifying a TRect.

Yes, it's unfortunate but there really isn't any way for the layer to know what and where you are drawing, before you are drawing it.

Btw, here's your example with the cross painted as marching ants (stippled).
[Issue 311 - Repaint TCustomLayer and draw TBitmapLayer at the same time.zip](https://github.com/graphics32/graphics32/files/15068238/Issue.311.-.Repaint.TCustomLayer.and.draw.TBitmapLayer.at.the.same.time.zip)

https://github.com/graphics32/graphics32/assets/18141921/533f8097-1a14-42f7-be28-0d251953b25b

**Comment by zedxxx** [comment]
I still think there is a bug somewhere in the caching/notification/messaging mechanism in GR32. If I change my original code like this:

```delphi
procedure TMainForm.imgMainMouseDown(Sender: TObject; Button: TMouseButton; Shift: TShiftState; X, Y: Integer; Layer: TCustomLayer);
begin
  FCurrent := Point(X, Y);
  
  imgMain.Invalidate;
  //FCustomLayer.Changed;

  FBitmapLayer.Bitmap.Clear(SetAlpha(clLightGreen32, 100));
end;
```
The code still doesn't work correctly. The only way to fix this is to call `Changed` and `Invalidate` together:

```delphi
imgMain.Invalidate;
FCustomLayer.Changed;
FBitmapLayer.Bitmap.Clear(SetAlpha(clLightGreen32, 100));
```
BUT there is no any visible problem when I call `Changed` (or single `Invalidate`) and draw TBitmapLayer from different notification events (e.g. from OnTimer and OnMouseDown):

```delphi
procedure TMainForm.imgMainMouseDown(Sender: TObject; Button: TMouseButton; Shift: TShiftState; X, Y: Integer; Layer: TCustomLayer);
begin
  FCurrent := Point(X, Y);
  FBitmapLayer.Bitmap.Clear(SetAlpha(clLightGreen32, 100));
end;

procedure TMainForm.tmr1Timer(Sender: TObject); // interval = 50 ms
begin
  imgMain.Invalidate;
end;
```

https://github.com/graphics32/graphics32/assets/6298130/9a756e57-999b-49ae-880e-1f581dfd62e2

**Comment by zedxxx** [comment]
This works:
```delphi
procedure TMainForm.imgMainMouseDown(Sender: TObject; Button: TMouseButton; Shift: TShiftState; X, Y: Integer; Layer: TCustomLayer);
begin
  FCurrent := Point(X, Y);

  imgMain.Invalidate;
  Application.ProcessMessages;

  FBitmapLayer.Bitmap.Clear(SetAlpha(clLightGreen32, 100));
end;
```

**Comment by zedxxx** [comment]
`Application.ProcessMessages` can be removed if you disable repaint optimizations: `imgMain.RepaintMode := rmFull`

**Comment by andersmelander** [comment]
> I still think there is a bug somewhere in the caching/notification/messaging mechanism in GR32. If I change my original code like this: [...] The code still doesn't work correctly. 

I can't reproduce any problem with that so there must be difference in our test code somewhere
I can't rule out that there's a bug somewhere but from what I've seen so far everything works as designed.


> Application.ProcessMessages can be removed if you disable repaint optimization

In this case the ProcessMessages just processes WM_PAINT messages so you could replace it with Update which does the same without any of the nasty side-effects of ProvcessMessages.

**Comment by zedxxx** [comment]
Yes, `Invalidate` + `Update` or `Invalidate` with TRect fix the problem. Single `Invalidate` doesn't work.
```delphi
procedure TMainForm.imgMainMouseDown(Sender: TObject; Button: TMouseButton; Shift: TShiftState; X, Y: Integer;
  Layer: TCustomLayer);
begin
  FCurrent := Point(X, Y);

  // 1. Invalidate + Update
  imgMain.Invalidate;
  imgMain.Update;

  // 2. Invalidate with TRect
  //imgMain.Invalidate(Rect(0, 0, imgMain.Width, imgMain.Height));

  FBitmapLayer.Bitmap.Clear(SetAlpha(clLightGreen32, 100));
end;
```
Which is the preferred way 1 or 2? Or are they doing the same thing at the same speed?

**Comment by andersmelander** [comment]
Number 1 is is probably the most efficient. There's also `TImage32.ForceFullInvalidate` which might be even more efficient as it disables repaint optimization for the current paint cycle.

For a full invalidation `TImage32.Invalidate`, without the call to `Update`, _should_ work.
`Update` simply processes WM_PAINT messages which _should_ happen automatically anyway unless you are doing all this in a tight loop where Windows doesn't get a chance to process the message queue.

If you take the code I posted above and change `InvalidateCross` to simply call `Invalidate` it should work (it does for me):
```delphi
procedure TMainForm.InvalidateCross(const p: TPoint);
begin
  imgMain.Invalidate;
end;
```

If that doesn't work then there's something else going on and we need to look at what Delphi version, Windows etc. you are using.

**Comment by zedxxx** [comment]
> If you take the code I posted above and change InvalidateCross to simply call Invalidate it should work (it does for me)

Yes, as I wrote before, it works from another event, but not from the same one. It's important to me. 

My modified test app: [CustomLayerTest.zip](https://github.com/graphics32/graphics32/files/15073939/CustomLayerTest.zip)

**Comment by andersmelander** [comment]
Thanks. I'll investigate later.
Until then you can use `TImage32.ForceFullInvalidate`. That should work.

**Comment by zedxxx** [comment]
> Until then you can use TImage32.ForceFullInvalidate. That should work.

Yes, this function works.

**Comment by andersmelander** [comment]
Okay, now I understand what's going on.

The problem is that you are using optimized repaint and drawing on the buffer without notifying the repaint optimizer what it needs to repaint.

`Invalidate` does a general invalidation of the buffer and asks Windows to repaint the control (i.e. generate a WM_PAINT message).
When the WM_PAINT message is processed and the buffer is being updated, the internal logic examines the "dirty" areas that needs to be repainted. If there are zero areas then everything is repainted, otherwise each area is repainted.

So when you have no visible layers, and have not invalidated any specific areas, then there are no dirty areas and everything is repainted. When you have a single visible layer, then the area covered by that layer is repainted. This matches what you are seeing exactly.

The solution is to disable the repaint optimizer, which you might as well do since you aren't using its features, by setting `RepaintMode=rmFull`. The other solution is to use `ForceFullInvalidate`, but it would be better to use `rmFull` and avoid the overhead of the repaint optimizer.
