### ISSUE TITLE
[dcc32 Error] GR32_R.dpk(73): E2029 Identifier expected but 'ASM' found

### ISSUE THREAD

**Issue by GabrielOnDelphi** [graphics32/graphics32#315]
[dcc32 Error] GR32_R.dpk(73): E2029 Identifier expected but 'ASM' found.
On Delphi 11.3

Because of this line in DPR:
  GR32.Blend.ASM in '..\..\GR32.Blend.ASM.pas',

**Comment by GabrielOnDelphi** [comment]
Solution: rename file to GR32.BlendASM.pas

**Comment by andersmelander** [comment]
I'm not sure what you did, but if you just open `GR32_R.dproj` or `GR32.groupproj` and build/compile/install then there should be no problem. The **asm** keyword is escaped in the project file to avoid this exact problem:
https://github.com/graphics32/graphics32/blob/d398e2c396bf6a8a363a193b8f5a544d05621a99/Source/Packages/D11%20and%20later/GR32_R.dpk#L73

I'm also using Delphi 11.3 and I'm pretty sure that it is _only_ if you somehow modify the package (e.g. add/remove files) that the IDE modifies the DPR source and removes the **&** escape.

**Comment by zedxxx** [comment]
I can't reproduce it at the moment, but I also get this error when installing GR32 from scratch on my laptop. IDE makes some changes in the dpr file and removes & sign. Resetting the changes and reopening the project fixed the issue.

I also get these two warnings when building GR32_R (is this somehow related?):
```
[dcc32 Warning] GR32_R.dpk(94): W1033 Unit 'GR32_VectorUtils.Reference' implicitly imported into package 'GR32_R'
[dcc32 Warning] GR32_R.dpk(94): W1033 Unit 'GR32.BigEndian' implicitly imported into package 'GR32_R'
```

**Comment by GabrielOnDelphi** [comment]
Isn't a better idea to just rename the file to something that Delphi does not protest against? :)
Personally, I do change some settings in the Project Options, so then the IDE changes the dpk file.

**Comment by andersmelander** [comment]
@zedxxx 

> I also get these two warnings when building GR32_R (is this somehow related?):

Yes it is. If you opt to add the two units and recompile then the IDE will modify the project source and the error will occur.
If you instead just choose to not add them and ignore the warning then the package will compile just fine.
![billede](https://github.com/graphics32/graphics32/assets/18141921/fb025cb2-6d37-47b3-b3ee-e9fc432fa5f0)

The only reason why these two units aren't already included is that I have to manually edit and sync the 18 package source files (for the different versions of Delphi/Lazarus) each time a unit is added or an option is changed and I really have better things to do with my time. Apart from this warning, which btw only occurs the first time you compile/install, there are no consequences of not having the units included in the unit list.

@GabrielOnDelphi 

> Isn't a better idea to just rename the file to something that Delphi does not protest against? :)

Maybe but this is where my stubbornness gets in the way and probably cloud my judgment; The unit name is valid and the problem is really a bug in the IDE.
I have made a decision to use dotted unit names going forward and I'm not going to make an exception here just because of an IDE bug that can be easily circumvented (if one knows how).
I guess I could just rename the file GR32.Blend.Assembler but again; Stubborn :-/ I guess this is what I will do eventually when I have a weak moment.

For now I will update the installation instructions when I get time so the problem is at least documented (which will help nobody, because I haven't released the [new documentation](https://melander.dk/graphics32/)).

I'm reopening the issue so I don't forget it.

**Comment by GabrielOnDelphi** [comment]
> my stubbornness gets in the way and probably cloud my judgment
We all have that :)

I also maintain a large personal library (now on github) and also other's libraries. I work a lot with DPK files.
So, when it is about the drp/dpk files, I have learned (long time ago) that it is better to let the IDE win this battle. Otherwise, you can't use Project Options.
It would be nice if one day Emba will let our manual changes in the dpr/dpk survive after we use "Project Options".
_

Usually when I get a new library from somewhere, I go directly to "Project Options" and set the LibSubfix to $(Auto).

___________________________________________________________________________________

> I also get these two warnings when building GR32_R (is this somehow related?)
This will create a problem **IF** that file is included in two packages. A PAS file can belong to one and only one package.
