### ISSUE TITLE
GR32_VectorUtils.pas has bug

### ISSUE THREAD

**Issue by GitCnSH-DSLIN** [graphics32/graphics32#34]
procedures of BuildDashedLine():
Line 2430:  if Length(Result[J]) = 0 then SetLength(Result, J);
Line 2527:  if Length(Result[J]) = 0 then SetLength(Result, J);

in Result[J] where J might be less than 0 in some case.

**Comment by GitCnSH-DSLIN** [comment]
Sorry, the first line number is 2430

**Comment by CWBudde** [comment]
I have now applied a simple fix which checks if J is greater or equal to zero. However, the problem might already be that it should not get negative in the first place. This said the code is likely not to crash anymore, but I don't know whether the output is still good in that case.

Please provide some code where J gets negative, so that we could have a closer look. Alternatively you can close the issue if everything works fine now.

**Comment by andersmelander** [comment]
Inactive
