### ISSUE TITLE
TBitmap32 constructor access violation

### ISSUE THREAD

**Issue by yesilcimenahmet** [graphics32/graphics32#43]
When I try this -> Bmp32 := TBitmap32.Create(1920, 1080); 

An Access violation occured, because that is going to TCustomMap Create constructor and FBackend was never created.

procedure TCustomBitmap32.ChangeSize(var Width, Height: Integer; NewWidth, NewHeight: Integer);
begin
 { FBackend is NIL }
  FBackend.ChangeSize(Width, Height, NewWidth, NewHeight);
end;

I fixed it as follows;

TCustomBitmap32 = class(TCustomMap)
public
constructor Create(Width, Height: Integer);reintroduce; overload; virtual;
....
end;

constructor TCustomBitmap32.Create(Width, Height: Integer);
begin
  Create;
  SetSize(Width,Height);
end;

Thanks.

**Comment by uuderzo** [comment]
I found the same issues using TBitmap32 in a C++ Builder XE8 code.
I initially thought that this were caused by a miscompilation of the Delphi code (I used DCC32 from command line) but after reading your post tried to remove TBitmap32 usage and the code worked correctly with other Graphics32 classes.
I didn't understand very well your fix. Did you modify Graphics32 source code or the way you call the constructor?
Thanks!
