### ISSUE TITLE
PolylineFS and TFloatRect

### ISSUE THREAD

**Issue by GrooverMD** [graphics32/graphics32#49]
Hi Peeps,

Got this code,

Outline : TArrayOfFloatPoint;
ARectangle : TFloatRec;

ARectangle.Left := 10.0;
ARectangle.Top := 10.0;
ARectangle.Right := 200.0;
ARectangle.Bottom := 200.0;

OutLine := Rectangle( ARectangle );
PolylineFS( PaintBox321.Buffer, Outline, clLime32, True, 1.0 );

This renders the rectangle with a 2 pixel outline not 1 as I would assume as the StrokeWidth is set to 1.0.

Setting the StrokeWidth to 0.5 only seems to modify the Alpha value of the color not the StrokeWidth, which is still 2 pixels wide.

Great library by the way, someone needs to write a book.

Cheers me old mates.

**Comment by CWBudde** [comment]
The problem is rather with the rect, but with the stroke width. Your code tries to draw a 1 pixel line at an integer position (like 10.0), which means that it starts precisely at 9.5 to 10.5 pixel. Rounded this means that both the pixel at the 9 position is affected and the pixel at the 10 position is affected. Both with a weight of 50%.

In order to achieve what you probably want, you need to use the outline as follows:

ARectangle.Left := 10.5;
ARectangle.Top := 10.5;
ARectangle.Right := 199.5;
ARectangle.Bottom := 199.5;

With integer coordinates and non-antialiased lines this is not needed (possible) as all coordinates are rounded. However, the above makes quite some sense in a bigger picture (if you don't want to draw just simple rectangles, but more complex shapes with arbitrary border widths.

If you want the old behaviour you could write some procedure like this:

```
procedure DrawOldFashionedRect(Left, Top, Right, Bottom, BorderWidth: TFloat);
var
  ARectangle: TFloatRect;
  Outline : TArrayOfFloatPoint;
begin
  ARectangle.Left := Left + 0.5 * BorderWidth;
  ARectangle.Top := Top + 0.5 * BorderWidth;
  ARectangle.Right := Right - 0.5 * BorderWidth;
  ARectangle.Bottom := Bottom - 0.5 * BorderWidth;

  OutLine := Rectangle(ARectangle);
  PolylineFS(PaintBox321.Buffer, Outline, clLime32, True, BorderWidth);
end;
```

**Comment by GrooverMD** [comment]
CWBudde,

Cheers for that, I will keep that in mind.

Regards.
