### ISSUE TITLE
ExtractSingleSpan crash

### ISSUE THREAD

**Issue by DumTiDum** [graphics32/graphics32#51]
GR32_VPR

around line 160:
    P := @Points[I];
    X := Round(P.X);   <--- P.X is a small negative number, X becomes -1

   SpanData[x]...   <--- x used to access array. Causes exception.

I draw a route (multiple lines between two points multiple times). When I pan right, causing the route to move left off screen, the crash happens.

I tried to set X := 0 (if < 0) but that eventually causes a crash somewhere else.

**Comment by DumTiDum** [comment]
I narrowed it somewhat down:

          StartPixel.x := 0;
          StartPixel.y := 46;
          StopPixel.x := -1;
          StopPixel.y := 45;
          af := Line( StartPixel.x, StartPixel.y, StopPixel.x, StopPixel.y);
          PolylineFS( bitmap, af, FColor, true, 2.5);

crashes.

**Comment by andersmelander** [comment]
I have not been able to reproduce the problem with the information you have provided and I suspect it's because my test bitmap is different from yours.
Can you provide us with a more complete example that reproduces the problem. E.g. something like:

```
var
  Bitmap: TBitmap32;
begin
  Bitmap := TBitmap32.Create(XXX, XXX);
  // Any additional details here...
  PolylineFS(Bitmap, Line(0, 46, -1, 45), clRed32, True, 2.5);
end;
```

**Comment by DumTiDum** [comment]
Hi, I didn't expect a response, so I didn't check here either (after I 'solved' the issue).

In GR32_VPR.pas I replaced round by trunc:

In function ExtractSingleSpan, line 162
  X := Trunc(P.X);

and in function IntegrateSegment, line 93
 X2 := Trunc(P2.X);

Seems to work for me, no crashes.

**Comment by andersmelander** [comment]
The following snippet reproduces the problem with FPC/Lazarus:

```
var
  Points: TArrayOfFloatPoint;
begin
  Points := Circle(0, 0, 4);
  PolygonFS(Bitmap, Points, clRed32);
end;
```

**Comment by andersmelander** [comment]
Based on #159 I'm guessing @DumTiDum experienced this with FPC.

**Comment by andersmelander** [comment]
I found a simple solution that seems to have solved the problem: Limit the precision of the VPR scanline segment X coordinates to 0.01 of a pixel.

**Comment by tomwiel** [comment]
> SpanData[x]... <--- x used to access array. Causes exception.

I don't know/use the VPR functions, but for me also something else looks suspicious here:
Perhaps the Delphi version has negative indices too, but only FPC causes the exception.
I know from experience, that FPC can have problems with negative indices and 
the solution was to use pointer math instead of "unbounded" array [0..0] types.
Perhaps someone with Delphi could check this?

**Comment by andersmelander** [comment]
> Perhaps someone with Delphi could check this?

I did :-) I'm primarily a Delphi developer and the only reason that I happened to have Lazarus installed (and accidentally reproduced this problem) was that I was working on #187.

I outlined the cause of the problem above: floating point rounding errors. The reason why Delphi didn't cause the exact same problem is that it's a different compiler which by chance produces slightly different assembler which in turn produced slightly different numbers. We're talking very tiny numbers here so it's not like one was right and the other was wrong. They were just different. The joys of working with floating point!
Once I had nailed the cause down I also managed to reproduce the problem in Delphi.

**Comment by tomwiel** [comment]
Yes, but for me the first question is whether the negative index (-1) should be seen as invalid.
The FPC exception has a technical cause: PSingleArray is declared for single element [0..0] and 64bit-FPC does not support access with negative longint. Type PSingleArray = ^Single; would solve this technically (if pointermath is enabled).

And the VPR author seems to have expected rounded results and -1:
SpanData reserves some pixels beyond the clipping width:
I := CX2 - CX1 + 4;   GetMem(SpanData, I * SizeOf(Single)); 
And he passes a pointer (@SpanData[-CX1 + 1]) which can allow (lowIndex = CX1-1).
I have not checked all this, but this looks like an indication that the code is prepared for rounding issues.

**Comment by andersmelander** [comment]
> I have not checked all this, but this looks like an indication that the code is prepared for rounding issues.

I agree that the code is prepared for _some_ rounding - after all it's operating on floating point coordinates which at some point will have to be translated to integer pixel coordinates. But apparently it's not prepared for rounding errors that brings the coordinates outside the clipping rect. At least not to the degree that it happened here.

I don't think the problem was that FPC has problems with the negative index. Otherwise it wouldn't work at all - and remember that I managed to reproduce the problem with Delphi too.

Let's look at `RenderPolyPolygon` (I'm mostly [rubber ducking](https://en.wikipedia.org/wiki/Rubber_duck_debugging) here):

1. The polygon is clipped to the `ClipRect`:
    ```
    for i := 0 to Len -1 do
      Poly[i] := ClipPolygon(Points[i], ClipRect);
    ```
    All points are now inside `ClipRect`.

2. The scanlines are built:
    ```
    BuildScanLines(Poly, ScanLines);
    ```
    This is where the error was introduced; Some of the scanlines were outside `ClipRect`.

3. Calculate the scanline width and allocate memory for the buffer:
    ```
    CX1 := Round(ClipRect.Left);
    CX2 := -Round(-ClipRect.Right) - 1;
    ```
    `CX1` is rounded down and `CX2` is rounded up. I'm not sure why the -1 is there but that doesn't really matter because we allocate 3 extra elements anyway (4-(Right-Left+1) = 3):
    ```
    I := CX2 - CX1 + 4;
    GetMem(SpanData, I * SizeOf(Single));
    ```
    I remembered that Matthias (the author) had problems with overflows so I looked at the VPR history surrounding the above.
    The early VPR code only allocated 1 extra element and had this comment:
    _`pad to the left and to the right to support floating point accumulation errors`_
    A few commits later that was increased to 2 extra elements and later again to the current 3 after reports of buffer overruns.
    This IMO shows that Matthias knew there was a problem but didn't know the exact cause. The easy solution was to just add a few more elements and move on.

4. Render each scanline.
    ```
    RenderScanline(ScanLines[I], RenderProc, Data, @SpanData[-CX1 + 1], CX1, CX2);
    ```
    `CX1` is the lower X bound of the ClipRect. We're passing `@SpanData[-CX1 + 1]` (which can be a negative address relative to the array) so that we don't need to subtract `CX1` when the array is indexed with X coordinates values. In theory, once the coordinates have been clipped, we should never encounter X values smaller than `CX1` but just to be sure there's a `+1` to take rounding errors into account.

5. `RenderScanline` calls `ExtractSingleSpan` passing the scanline and the SpanData array pointer:
    ```
    ExtractSingleSpan(ScanLine, Span, SpanData);
    ```

6. `ExtractSingleSpan ` iterates the scanline list and for each element it gets the X coordinate, **rounds it down** and uses the values as an index into the SpanData array:
    ```
    X := Round(P.X);
    fracX := P.X - X;
    SpanData[X] := SpanData[X] + (1 - fracX); 
    ```
    This is where the error occurs: The value of `X` is less than `-(-CX1 + 1)` (from step 4) which causes a buffer underrun.

Since `X = -1` when the error occurs this means:

  `-1 < -(-CX1+1)` -> 
  `CX1 > 0` ->
  `Round(ClipRect.Left) > 0`

This makes little sense to me since `ClipRect.Left = 0`. I guess I'll have to look at the problem again...

Another thing that I've been wondering is if Matthias forgot that rounding mode has been set to `rmDown` so this:
```
X := Round(P.X); // Round toward negative infinity
```
should in fact have been:
```
X := Int(P.X); // Round toward zero
```

**Comment by andersmelander** [comment]
Okay I think I found it.

This is the code where the AV occurs:
```
SpanData[X] := SpanData[X] + (1 - fracX); Inc(X);
```
On FPC the above is compiled to:
```
mov     rax,[rbp-$18]
mov     edx,[rbp-$20]
movss   xmm1,[rdx*4+rax]
subss   xmm1,xmm0
mov     rax,[rbp-$18]
mov     edx,[rbp-$20]
movss   [rdx*4+rax],xmm1
add     dword ptr [rbp-$20],$01
```
The only important part here is `SpanData[X]` and we're interested in what happens when X=-1 so let's look at the assembly for that part:
```
mov     rax,[rbp-$18]
mov     edx,[rbp-$20]
movss   xmm1,[rdx*4+rax]
```
Can you spot the bug?

`rax` contains the `SpanData` pointer and `edx` contains `X`.
`[rdx*4+rax]` is supposed to reference `SpanData[X]` but notice that it's using the 64 bit `rdx` register and we only loaded `X` into the lower 32 bits (via the `edx` register).
This works fine for positive values but "less fine" for negative values. For example if X=-1 then `edx = $FFFFFFFF` (i.e. -1) but `rdx=$00000000FFFFFFFF` (i.e. 4.294.967.295)... Boom!

I believe this can be classified as a FPC compiler bug. FWIW Delphi correctly loads the index into a 64 bit register so it doesn't suffer from the same problem.

The easy workaround for FPC is to simply declare `X` as a `Int64`. That takes care of this particular AV but it also reveals that the same problem exists other places in the code. For example in the call to `CumSum`.

**Comment by tomwiel** [comment]
Yes int64 is the workaround. Few years ago,  there was a Lazarus forum post about such limitation (unrelated to gr32), but I cannot find this anymore. Essentially the problem was with declared array[0..0] even under {$R-}: 
Code is unsafe for negative index if (sizeOf(indexVariable) < sizeOf(nativeInteger)), and the explanation was somewhat like this:  signed integer (-1) is internally converted to unsigned integer (high(i)), because FPC treats the range type as unsigned.
Since that time I avoid such array declarations for unbounded access wherever I can.

**Comment by tomwiel** [comment]
But a FPC bug report would not help, because they classified the declared index range as invalid for other indices, thus the compiler is free to unsupport this.

**Comment by andersmelander** [comment]
Probably this one: https://forum.lazarus.freepascal.org/index.php/topic,44655.0.html

> But a FPC bug report would not help, because they classified the declared index range as invalid for other indices, thus the compiler is free to unsupport this.

The arguments in that thread against fixing the problem is pure ego driven bullshit. Regardless it does seem like a bug report would be a waste of time.

**Comment by tomwiel** [comment]
> Probably this one: https://forum.lazarus.freepascal.org/index.php/topic,44655.0.html

Yes, I meant this.
