### ISSUE TITLE
BlendMemEx($FFxxxxxx, 0, 255) loses alpha

### ISSUE THREAD

**Issue by andersmelander** [graphics32/graphics32#53]
The operation BlendMemEx($FF494949, 0, 255) produces different results depending on which implementation is used - and only the pascal versions produce the correct result.
### Test case
```
  Color := 0;
  BlendMemEx_Reference($FF494949, Color, 255);
  Assert(Color = $FF494949);
```
### Results
| Function | Result | Valid |
-----------|---------|------
| `BlendMemEx_Reference` | $FF494949 | Correct |
| `BlendMemEx_Pas` | $FF494949 | Correct |
| `BlendMemEx_ASM` | $**00**494949 | Wrong |
| `BlendMemEx_MMX` | $**FE**494949 | Wrong |
| `BlendMemEx_SSE2` | $**FE**494949 | Wrong |

The problem can be seen when rendering a polygon filled with an opaque gradient onto a transparent/clear bitmap. The resulting polygon should be opaque but isn't.

Considering that there appears to be an (out of date) unit test that verifies this function, it's a bit strange that this problem hasn't been discovered before...

**Comment by CWBudde** [comment]
The problem has been discovered before and in fact the unit test was written to remind us that this bug exists.

Unfortunately it's not that easy to solve as the issue is slightly by-design.

When the library was written, computers were way slower than nowadays and a high quality graphic library for Delphi was not available (and GDI+ was very slow). To gain speed some "optimizations" were made. For example (and this is the most problematic one) the multiplication of two bytes was simplified to

`ByteResult = (ByteA * ByteB) shr 8 = (ByteA * ByteB) div 256` 

when it actually should be

`ByteResult = (ByteA * ByteB + 127) div 255`

You have to keep in mind that a shift is way faster than a division. This was good enough for the initial purpose of the library to power the graphic rendering of a toolbar. For that need, it's not really important whether black is really black or white is 100% white.

To minimize the problem, an additional bias has been added later (at least), but the main problem still persists.

The solution would be to reintroduce the correct div. However, that will slow down the blend functions and means that the whole code must be reviewed in this regard, as wrong division were used elsewhere as well.

On the other hand, the library isn't (wasn't) really meant for to produce the best visual result. For example: Several algorithms would need to use 16 bit color values for internal calculations in order to produce good results.

Or take the gamma handling, which until last week was all mixed up. Typically modern monitors use a gamma factor of 2.2 or in fact the transfer function defind by sRGB. In contrast to that GR32 used a value of 0.7 by default (at least according to the documentation). Actually this was rather 1 / 0.7 as the gamma table was calculated inverse (as it was used to encode gamma values not to decode). Still it didn't match the gamma settings which we use today.

The latter has been corrected to some degree, but it still uses one master gamma value. If you want to mix a non-gamma corrected image with an image of a different gamma setting then there is no simple way currently.

Not to mention the fact that the blending does not take the gamma values into account. While the latter is not always really necessary, it is necessary when you want to blur an image. For this reason, a new gamma corrected blur algorithm has been introduced. Still it lacks precision, because it just uses 8 bit, while a 16 bit table would even improve the visual appearance.

As the version 2.0 still has the "beta" label, I'm unsure whether it makes sense to "fix" all the issues or even if it is OK for the users if a few things will be improved (probably breaking some existing code here and there)?

A solution could be to split the library into one fast library meant to draw fast regardless of the visual appearance and a library for quality image processing. It's just that for the latter there is not much resources (both human and in terms of code already written with this in mind).

For now, I'd be happy if at least the wrong alpha could get fixed, but I'm not there yet (looking through the code over the weekend).

**Comment by andersmelander** [comment]
We're getting into a bit of a philosophical discussion about the purpose of GR32 here, but for me GR32 is a low level toolbox for 32-bit RGBA manipulation. IMO it needs to do that as correctly as possible.

I do remember having discussed this problem before with Mattias about a decade ago and I  actually thought that we had already fixed it, but I've been comparing the source from back then and, apart from what appears to be a bug fix for the MMX version, BlendMemEx hasn't been modified since then.

I can see from my copy of the old graphics32 usenet archive that the "(A*B) shr 8" problem was fixed several places, but apparently Blend wasn't one of them. I think the reason might be that in the cases where one cares about the alpha Merge should used instead of Blend - and that is indeed also the case for me here...

I don't know why I didn't notice this before: GR32_ColorGradients only uses Blend* - it should either use Merge* or delegate the decision to the user. I'll create a separate issue for that.

With regard to Gamma, for my purposes I prefer, and actually need, not to have any Gamma correction done until I explicitly apply it at the presentation stage (if at all). I don't want the Gamma correction to mess with my RGBA values during all the low level merge and drawing of primitives.
It's a bit like the ClearType style LCD AA functionality; If you're drawing text directly to the screen then it makes sense to apply LCD AA, but if you're drawing onto a bitmap that will be processed further then it makes no sense and will just make the text look bad.

**Comment by andersmelander** [comment]
Blend* isn't supposed to do composition on the alpha channel. Kinda "works as designed".

**Comment by CWBudde** [comment]
Yes it's getting a bit philosophical here. You're indeed right that you probably want to do gamma processing only as the last step. On the other hand the gamma preprocessing is also there to gain more precision (either on the darker range or the brighter range, depending on its setting). This makes sense since we're only using the limited range of one byte per channel.

Regarding 'blend': I have already corrected this in the non '*Ex' functions and in the documentation where it now reads in particular that blend is meant for blending to a fully opaque background. For those who wonder about this, please see [the Alpha compositing/blending section on wikipedia](https://en.wikipedia.org/wiki/Alpha_compositing#Alpha_blending). The second equation is more or less the blend function we have today (and where it come from -> a special case of the merge operation).

This said, all blend* functions should take this into account.
