### ISSUE TITLE
Dependency on TBitmap for file storage operations.

### ISSUE THREAD

**Issue by AngusJohnson** [graphics32/graphics32#57]
I'm wondering whether it might be better to move away from TBitmap32's dependency on TBitmap for file storage operations. To that end I've written a module that does read and write BMP formats and tested it with Jason Summers' test [BMP suite](http://entropymine.com/jason/bmpsuite/). Is this likely to be of interest? (I am aware that TBitmap does also read and write other formats eg ICO & CUR.)

**Comment by CWBudde** [comment]
With the GR32PNG library we also have a second option to store TBitmap32. I haven't integrated this directly into GR32, because so far GR32 was not meant to have file support.

Indeed I fear that once we add support for that on a large scale (that is far beyond native Bitmap storage), the users would ask for even more file formats. And implementing that would make this library even harder to maintain.

Personally, I lately tend not to have big monolithic as we used to have with Delphi projects, but rather to subdivide the code into several packages. This creates different problems (of keeping the packages compatible), but the advantage of different development cycle times (fast times for actively developed packages) can often be an advantage.

Maybe we should consider adding some sort of API where other libraries can easily dock in, especially in regards of file support. Of course it would be easier for the user to have it monolithic in the end, but using submodules with git it's possible to fetch external dependencies automatically.

**Comment by AngusJohnson** [comment]
Hi Christian.

Yes, I entirely agree with you reservations re monolithic libraries, and in many ways Graphics32 is already monolithic*. And of course you're right about where to stop with a seemingly endless list for image file formats. (Though on that note I have found your PNG library indispensable.) 

*At one point I  tried to rationalize TBitmap32's excessive (IMHO) list of line functions, since I believe many of these are now redundant with the inclusion of Mattias' GR32_Polygons module, and that task ended up being beyond my patience.

Anyhow, thanks again for the huge effort you seem to be putting in to getting Graphics32 ver 2 finished. (I would have like to have assisted but my own health issues have limited what I can do.)

**Comment by andersmelander** [comment]
I'm late to the party (and you closed the issue while I started writing), but I just wanted to say that I agree with Christian; I think Graphics32 should concentrate on the core functionality and leave stuff like file formats to external libraries.
Also for the record TBitmap doesn't support ICO and CUR. We have TIcon for that.
Anyway, Angus, do you have a repository with your BMP library somewhere? I'd like to have a look.

**Comment by AngusJohnson** [comment]
> and you closed the issue while I started writing

:)

> Anyway, Angus, do you have a repository with your BMP library somewhere?

I've just updated it with a few bugfixes (and hope I haven't broken anything) ...
http://angusj.com/temp/Format_BMP.zip
