### ISSUE TITLE
a strange picture

### ISSUE THREAD

**Issue by inxworld** [graphics32/graphics32#7]
![error](https://cloud.githubusercontent.com/assets/8032860/23643535/65505602-033d-11e7-93aa-ef94108c3412.gif)

I found a strange picture !  
graphics32-2.0  
    TImage32.load   get  "Can't allocate DIB handle"
graphics32 RX1   
   TImage32.load  is ok, but IDE-"save all" get "out of memory"
  
![1](https://cloud.githubusercontent.com/assets/8032860/23643874/599fdd6c-033f-11e7-92a9-b94043e37553.png)

**Comment by CWBudde** [comment]
Based on the supplied call stack the problem doesn't directly come from GR32. However, it might come indirectly from GR32 as the IDE might try to store the image in the dfm file, which fails because it is invalid or too big.

Before this you load the gif file (which is not officially supported) by using the design editor for the TBitmap32. This does not know any graphic format beyond Bitmap (BMP) by itself. For all other formats the Delphi libraries (like TPicture) are used. For some reasons these throw the exception and might result in invalid states.

Eventually it can be handled better on the GR32 side (to avoid invalid graphics), but after about an hour of work, I don't know exactly how this can happen. It would need to handle exceptions internally to fix the image with a 'workaround' solution (eventually showing the exception message as warning). However, this will most probably decrease the flexibility in the way that the software has to degrade (crop) the image automatically.

To make it short: The supplied image is too large to load inside the IDE (where GDI handles are rare). If you load it on runtime it shouldn't be an issue though.
