### ISSUE TITLE
Destroying state in TNotifiablePersistent

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#74]
raising "Changed" in the destructor of any decendent of TNotifiablePersistent could cause unexpected behavior since the object is partially freed .

the added code need more optimization :
protected
  ...
  FIsDestroying:boolean;

procedure TNotifiablePersistent.Beforedestruction;
begin
  FIsDestroying:=True;
end;
procedure TNotifiablePersistent.Changed;
begin
   if not FIsDestroying and  (FUpdateCount = 0) and Assigned(FOnChange) then FOnChange(Self);
end;

**Comment by andersmelander** [comment]
You're probably right but before we try to fix this we need to better understand what causes the problem - i.e. what causes `Changed` to be called during destruction. It might be that we can solve the problem at a higher level.

Do you have an example of a scenario that reproduces the problem?

**Comment by lamdalili** [comment]
in the common behavior, imagine a class with Clear that use Changed, it is very likely that Clear will be called in the destructor.

**Comment by lamdalili** [comment]
here a concrete example.
TMyClass=class(TNotifiablePersistent)
public
  procedure Clear();virtual;
  destructor Destroy();override;
end;
TMyClass2=class(TMyClass)
public
  List:TStrings;
  procedure Clear();override;
  procedure _Change(Sender:TObject);
  procedure Add(const item:string);
  constructor Create();
  destructor Destroy();override;
end;

{ TMyClass }

procedure TMyClass.Clear;
begin
  // do something
  Changed();
end;

destructor TMyClass.Destroy;
begin
  Clear();
  inherited;
end;

{ TMyClass2 }

procedure TMyClass2.Add(const item: string);
begin
   List.Add(Item);
   Changed();
end;

procedure TMyClass2.Clear;
begin
  List.Clear;
  inherited;
end;

constructor TMyClass2.Create;
begin
  List:=TStringList.Create;
  OnChange:=_Change;
end;

destructor TMyClass2.Destroy;
begin
  FreeAndNil(List);
  inherited; //here changed is called in the ancestor
             //which use List been freed
end;

procedure TMyClass2._Change(Sender: TObject);
begin
   //  do something...
   with TMyClass2(Sender) do
     Showmessagefmt('%s',[List.Text]);
end;

the test code
var
  T:TMyClass2;
begin
    T:=TMyClass2.Create;
    T.Add('a');
    T.Add('b');
    T.Free;
end;

**Comment by andersmelander** [comment]
I'm sorry but that's a contrived example.
What I'm asking for is an example that reproduces the problem using the standard Graphics32 classes.

It is an obvious bug in your example that Clear is called from the destructor (because of the side effects). That is not something which should be worked around by the framework.

**Comment by AngusJohnson** [comment]
> I'm sorry but that's a contrived example.

While I agree it's contrived, nevertheless I think lamdalili makes a reasonable argument that there's still a weakness there that could very easily be addressed.

**Comment by andersmelander** [comment]
Yes, it can easily be addressed but doing so adds unnecessary complexity (minor, but still) to an **internal** low level class that basically works as designed.

I don't see the current design as a weakness. It's fairly common that there are certain things that shouldn't be done during destruction. In this case calling a method that ends up calling modified is obviously one of them. The solution is easy: Don't do it. Any error caused by calling Changed during destruction is not a weakness but a bug in the _use_ of `TNotifiablePersistent`.
Implementing the suggested change would be solving the symptom (by allowing incorrect use of Changed) instead of solving the problem (if there actually is one).

I'm still interested to see if OP can provide a non-contrived example that demonstrates an actual problem.

**Comment by AngusJohnson** [comment]
>  The solution is easy: Don't do it.

That's easy to say but I can also see the wisdom of defensive programming, especially given the size and complexity of this library and the number of contributors. Currently we're relying on contributors remembering to calling `BeginUpdate` before any code (in a destructor) that might trigger a `Changed` event. While I don't feel strongly about this, I am in favor of lamdalili's proposal.

**Comment by andersmelander** [comment]
Do you have any examples of where `BeginUpdate` is used like that (in the destructor)?

and then there's stuff like this:

```
type
  TButWhatAboutThisThen = class(TNotifiablePersistent)
  private
    FWhoopeydo: TWhoopeydo;
  public
    procedure Changed; override;
  end;

procedure TButWhatAboutThisThen.Changed;
begin
  FWhoopeydo.CrashAndBurn;
  inherited;
end;
```

**Comment by AngusJohnson** [comment]
> Edit: Never mind. Found it: TCustomBitmap32.Destroy

Yes, and also `TLayerCollection` and probably others.

And in these classes, I suggest their destructors would also benefit (ie be safer) from this modification ...
`TCustomBackend` `TNestedTransformation` `TBrushCollection` `TPointerMap`

**Comment by andersmelander** [comment]
> `inc(FUpdateCount);`

I think this is a good solution.
It doesn't take care of the potential problem with the overridden `Changed` method though but that is unavoidable without a redesign of the class.
