### ISSUE TITLE
cant install on Delphi Tokyo

### ISSUE THREAD

**Issue by protoror** [graphics32/graphics32#8]
1) I change GR32_Compiler.inc
https://www.dropbox.com/s/a0mm2mk8m1fq01g/GR32_Compiler.inc?dl=0
2) try install and get Access violation at address 289D8799 in module 'bds.exe'. Read of address 00000010.

**Comment by micha137** [comment]
1. Thank you for the feedback.  Please make a diff and/or pull request instead of posting a file somewhere.  A diff makes it easier to for us to see what you changed.

2. Most of us developers will not have Delphi Tokyo, so we cannot reproduce the AV.  To debug the AV you could debug the Delphi IDE with the Delphi IDE using  "Start" -> "Load Process.." or "Start" -> "Connect to Process.,." (I have a German XE3, so don't know the exact wording of menu entries).  You could then post a stack trace here, which is much more useful than the AV address, which might differ after each compile.

**Comment by protoror** [comment]
clear old Berlin BPL and all work, sorry
