### ISSUE TITLE
Infinite recursion in VertexReduction

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#87]
If VertexReduction called with closed path an infinite recursion will result in RamerDouglasPeucker
I am not sure to understand the code but when I replace > with >= seems work  
code in RamerDouglasPeucker
```
    for Index := FirstIndex + 1 to LastIndex - 1 do
    begin
      with Points[LastIndex] do
        Delta := Abs((Points[Index].x - x) * (Points[FirstIndex].y - y) -
          (Points[Index].y - y) * (Points[FirstIndex].x - x));
      if Delta >= DeltaMax then  // instead of '>'
      begin
        DeltaMaxIndex := Index;
        DeltaMax := Delta;
      end;
    end;
```

**Comment by andersmelander** [comment]
The implementation of the _Ramer-Douglas-Peucker_ algorithm appears to be correct although it is a bit strange that the float and fixed implementations uses different methods of calculating the point to line distance (and both seem to do it wrong: distance to **line** <= distance to **line segment**).

I don't have time to create a reproducible test case and I have not been able to spot the cause of any infinite recursions by looking at the code or running it in my head, so I'm afraid I'll have to defer this to @CWBudde who is the one that implemented this.

**Comment by CWBudde** [comment]
I can confirm the issue, but at the moment I don't have time for this. I'll put it on my todo list for after the summer holiday.

**Comment by andersmelander** [comment]
I implemented the suggested fix and a bunch of optimizations.
I also removed the fixed point version since it frequently suffered from unavoidable integer overflows in the distance calculations. The fixed point VertexReduction now simply converts back and forth to/from floating point and use the float version of VertexReduction. Slow but I'm pretty sure nobody uses it anyway (since it was badly broken).

I have not done anything about the use of _point-to-line distance_ instead of _point-to-line-segment distance_ since every other implementation I've looked at also appears to be using point-to-line distance. Probably because it's "good enough" and much faster and easier to implement.

The LineSimplification example also got some love:
![billede](https://github.com/user-attachments/assets/9213f019-7c11-403d-ab19-3711659e2d93)
