### ISSUE TITLE
Better granularity in layer change notification

### ISSUE THREAD

**Issue by andersmelander** [graphics32/graphics32#89]
I proposed a new event 'OnScaleShiftChange'  because  some thing is wrong when using changed in line  Layers[i].Changed  .. here we force raising a possible heavy opeartions and when the scale changed is not the probleme of the Layer but it must be notified and see if any updating is needed.

      for i := 0 to Layers.Count - 1 do
        Layers[i].OnScaleShiftChange;

_Originally posted by @lamdalili in https://github.com/graphics32/graphics32/issues/35#issuecomment-499500783_

**Comment by lamdalili** [comment]
I think the best solution is to implement OnScaleShiftChange in LayerCollection this helps to avoid redendent usage of OnGetViewportScale and OnGetViewportShift when scalling points

**Comment by lamdalili** [comment]
Radical solution is to put scaleX,scaleY,shiftX,shiftY all togother in a transformation this will make TCustomImage32 compatible with TCanvas32,PolylineFS and PolygonFS 
with this modification you can replace OnGetViewportScale and OnGetViewportShift in TLayerCollection by the transformation ...
if you are ok with this idea don't forget to add virtual method to create tramsformation
CreateTransformation;

finally TLayerCollection.OnScaleShiftChange is called directely or indirectely from Transformation.OnChange

**Comment by lamdalili** [comment]
I propose this code for `TCustomImage32.SetXForm` because `DoOnScaleChange` is only depending on scale value ...there are some situations when bitmap is implicitly scaled without notification(to create new resolution for new size) usually with these scale mode smStretch,  smResize, smOptimal and  smOptimalScaled ie when changing size of TCustomImage32 or maximaze the mainform when  `TCustomImage32.Align <>alNone` .

Be carefull handling this with  `TCustomImage32.Resize` or any of its variant will not always work since scale operation is independant form size of TCustomImage32  for example in  `PaintTo`


```
procedure TCustomImage32.SetXForm(ShiftX, ShiftY, ScaleX, ScaleY: TFloat);
var
 ShiftChanged,ScaleChanged:boolean;
begin
  ShiftChanged:=(CachedShiftX<> ShiftX) or (CachedShiftY <> ShiftY);
  ScaleChanged:=(CachedScaleX<> ScaleX) or (CachedScaleY <> ScaleY);
  CachedShiftX := ShiftX;
  CachedShiftY := ShiftY;
  CachedScaleX := ScaleX;
  CachedScaleY := ScaleY;
  if (ScaleX <> 0) then
    CachedRecScaleX := 1 / ScaleX
  else
    CachedRecScaleX := 0;

  if (ScaleY <> 0) then
    CachedRecScaleY := 1 / ScaleY
  else
    CachedRecScaleY := 0;
  if ShiftChanged or ScaleChanged then
     OnScaleShiftChange(ShiftChanged,ScaleChanged); //or OnXFormChange
end;
```

**Comment by andersmelander** [comment]
I still don't understand the purpose of this change. If I'm to do anything about it then it will need better specs.
